package aws

import "github.com/hashicorp/terraform/helper/schema"

type TerraformResourceType int
const (
	DataSource TerraformResourceType = iota
	Resource
 )

type TerraformResource struct {
	Type TerraformResourceType
	Name string
	Value *schema.Resource
}

func DataSources() []TerraformResource {
	return []TerraformResource{
		TerraformResource{DataSource, "dataSourceAwsAcmCertificate", dataSourceAwsAcmCertificate()},
		TerraformResource{DataSource, "dataSourceAwsAcmpcaCertificateAuthority", dataSourceAwsAcmpcaCertificateAuthority()},
		TerraformResource{DataSource, "dataSourceAwsAmi", dataSourceAwsAmi()},
		TerraformResource{DataSource, "dataSourceAwsAmiIds", dataSourceAwsAmiIds()},
		TerraformResource{DataSource, "dataSourceAwsApiGatewayRestApi", dataSourceAwsApiGatewayRestApi()},
		TerraformResource{DataSource, "dataSourceAwsArn", dataSourceAwsArn()},
		TerraformResource{DataSource, "dataSourceAwsAutoscalingGroups", dataSourceAwsAutoscalingGroups()},
		TerraformResource{DataSource, "dataSourceAwsAvailabilityZone", dataSourceAwsAvailabilityZone()},
		TerraformResource{DataSource, "dataSourceAwsAvailabilityZones", dataSourceAwsAvailabilityZones()},
		TerraformResource{DataSource, "dataSourceAwsBatchComputeEnvironment", dataSourceAwsBatchComputeEnvironment()},
		TerraformResource{DataSource, "dataSourceAwsBatchJobQueue", dataSourceAwsBatchJobQueue()},
		TerraformResource{DataSource, "dataSourceAwsBillingServiceAccount", dataSourceAwsBillingServiceAccount()},
		TerraformResource{DataSource, "dataSourceAwsCallerIdentity", dataSourceAwsCallerIdentity()},
		TerraformResource{DataSource, "dataSourceAwsCanonicalUserId", dataSourceAwsCanonicalUserId()},
		TerraformResource{DataSource, "dataSourceAwsCloudFormationExport", dataSourceAwsCloudFormationExport()}, // dataSourceAwsCloudformationExport(),
		TerraformResource{DataSource, "dataSourceAwsCloudFormationStack", dataSourceAwsCloudFormationStack()}, // dataSourceAwsCloudformationStack(),
		TerraformResource{DataSource, "dataSourceAwsCloudTrailServiceAccount", dataSourceAwsCloudTrailServiceAccount()}, // dataSourceAwsCloudtrailServiceAccount(),
		TerraformResource{DataSource, "dataSourceAwsCloudwatchLogGroup", dataSourceAwsCloudwatchLogGroup()},
		TerraformResource{DataSource, "dataSourceAwsCognitoUserPools", dataSourceAwsCognitoUserPools()},
		// dataSourceAwsCommonSchema(),
		TerraformResource{DataSource, "dataSourceAwsDbInstance", dataSourceAwsDbInstance()},
		TerraformResource{DataSource, "dataSourceAwsDbSnapshot", dataSourceAwsDbSnapshot()},
		TerraformResource{DataSource, "dataSourceAwsDynamoDbTable", dataSourceAwsDynamoDbTable()}, // dataSourceAwsDynamodbTable(),
		TerraformResource{DataSource, "dataSourceAwsEbsSnapshot", dataSourceAwsEbsSnapshot()},
		TerraformResource{DataSource, "dataSourceAwsEbsSnapshotIds", dataSourceAwsEbsSnapshotIds()},
		TerraformResource{DataSource, "dataSourceAwsEbsVolume", dataSourceAwsEbsVolume()},
		TerraformResource{DataSource, "dataSourceAwsEcrRepository", dataSourceAwsEcrRepository()},
		TerraformResource{DataSource, "dataSourceAwsEcsCluster", dataSourceAwsEcsCluster()},
		TerraformResource{DataSource, "dataSourceAwsEcsContainerDefinition", dataSourceAwsEcsContainerDefinition()},
		TerraformResource{DataSource, "dataSourceAwsEcsService", dataSourceAwsEcsService()},
		TerraformResource{DataSource, "dataSourceAwsEcsTaskDefinition", dataSourceAwsEcsTaskDefinition()},
		TerraformResource{DataSource, "dataSourceAwsEfsFileSystem", dataSourceAwsEfsFileSystem()},
		TerraformResource{DataSource, "dataSourceAwsEfsMountTarget", dataSourceAwsEfsMountTarget()},
		TerraformResource{DataSource, "dataSourceAwsEip", dataSourceAwsEip()},
		TerraformResource{DataSource, "dataSourceAwsEksCluster", dataSourceAwsEksCluster()},
		TerraformResource{DataSource, "dataSourceAwsElasticBeanstalkHostedZone", dataSourceAwsElasticBeanstalkHostedZone()},
		TerraformResource{DataSource, "dataSourceAwsElasticBeanstalkSolutionStack", dataSourceAwsElasticBeanstalkSolutionStack()},
		TerraformResource{DataSource, "dataSourceAwsElastiCacheCluster", dataSourceAwsElastiCacheCluster()}, // dataSourceAwsElasticacheCluster(),
		TerraformResource{DataSource, "dataSourceAwsElasticacheReplicationGroup", dataSourceAwsElasticacheReplicationGroup()},
		TerraformResource{DataSource, "dataSourceAwsElb", dataSourceAwsElb()},
		TerraformResource{DataSource, "dataSourceAwsElbHostedZoneId", dataSourceAwsElbHostedZoneId()},
		TerraformResource{DataSource, "dataSourceAwsElbServiceAccount", dataSourceAwsElbServiceAccount()},
		TerraformResource{DataSource, "dataSourceAwsGlueScript", dataSourceAwsGlueScript()},
		TerraformResource{DataSource, "dataSourceAwsIamAccountAlias", dataSourceAwsIamAccountAlias()},
		TerraformResource{DataSource, "dataSourceAwsIAMGroup", dataSourceAwsIAMGroup()}, // dataSourceAwsIamGroup(),
		TerraformResource{DataSource, "dataSourceAwsIAMInstanceProfile", dataSourceAwsIAMInstanceProfile()}, // dataSourceAwsIamInstanceProfile(),
		TerraformResource{DataSource, "dataSourceAwsIAMPolicy", dataSourceAwsIAMPolicy()}, // dataSourceAwsIamPolicy(),
		TerraformResource{DataSource, "dataSourceAwsIamPolicyDocument", dataSourceAwsIamPolicyDocument()},
		TerraformResource{DataSource, "dataSourceAwsIAMRole", dataSourceAwsIAMRole()}, // dataSourceAwsIamRole(),
		TerraformResource{DataSource, "dataSourceAwsIAMServerCertificate", dataSourceAwsIAMServerCertificate()}, // dataSourceAwsIamServerCertificate(),
		TerraformResource{DataSource, "dataSourceAwsIAMUser", dataSourceAwsIAMUser()}, // dataSourceAwsIamUser(),
		TerraformResource{DataSource, "dataSourceAwsInspectorRulesPackages", dataSourceAwsInspectorRulesPackages()},
		TerraformResource{DataSource, "dataSourceAwsInstance", dataSourceAwsInstance()},
		TerraformResource{DataSource, "dataSourceAwsInstances", dataSourceAwsInstances()},
		TerraformResource{DataSource, "dataSourceAwsInternetGateway", dataSourceAwsInternetGateway()},
		TerraformResource{DataSource, "dataSourceAwsIotEndpoint", dataSourceAwsIotEndpoint()},
		TerraformResource{DataSource, "dataSourceAwsIPRanges", dataSourceAwsIPRanges()}, // dataSourceAwsIpRanges(),
		TerraformResource{DataSource, "dataSourceAwsKinesisStream", dataSourceAwsKinesisStream()},
		TerraformResource{DataSource, "dataSourceAwsKmsAlias", dataSourceAwsKmsAlias()},
		TerraformResource{DataSource, "dataSourceAwsKmsCiphertext", dataSourceAwsKmsCiphertext()},
		TerraformResource{DataSource, "dataSourceAwsKmsKey", dataSourceAwsKmsKey()},
		TerraformResource{DataSource, "dataSourceAwsKmsSecret", dataSourceAwsKmsSecret()},
		TerraformResource{DataSource, "dataSourceAwsLambdaFunction", dataSourceAwsLambdaFunction()},
		TerraformResource{DataSource, "dataSourceAwsLambdaInvocation", dataSourceAwsLambdaInvocation()},
		TerraformResource{DataSource, "dataSourceAwsLb", dataSourceAwsLb()},
		TerraformResource{DataSource, "dataSourceAwsLbListener", dataSourceAwsLbListener()},
		TerraformResource{DataSource, "dataSourceAwsLbTargetGroup", dataSourceAwsLbTargetGroup()},
		TerraformResource{DataSource, "dataSourceAwsMqBroker", dataSourceAwsMqBroker()},
		TerraformResource{DataSource, "dataSourceAwsNatGateway", dataSourceAwsNatGateway()},
		TerraformResource{DataSource, "dataSourceAwsNetworkInterface", dataSourceAwsNetworkInterface()},
		TerraformResource{DataSource, "dataSourceAwsPartition", dataSourceAwsPartition()},
		TerraformResource{DataSource, "dataSourceAwsPrefixList", dataSourceAwsPrefixList()},
		TerraformResource{DataSource, "dataSourceAwsRdsCluster", dataSourceAwsRdsCluster()},
		TerraformResource{DataSource, "dataSourceAwsRedshiftCluster", dataSourceAwsRedshiftCluster()},
		TerraformResource{DataSource, "dataSourceAwsRedshiftServiceAccount", dataSourceAwsRedshiftServiceAccount()},
		TerraformResource{DataSource, "dataSourceAwsRegion", dataSourceAwsRegion()},
		TerraformResource{DataSource, "dataSourceAwsRoute", dataSourceAwsRoute()},
		TerraformResource{DataSource, "dataSourceAwsRoute53Zone", dataSourceAwsRoute53Zone()},
		TerraformResource{DataSource, "dataSourceAwsRouteTable", dataSourceAwsRouteTable()},
		TerraformResource{DataSource, "dataSourceAwsS3Bucket", dataSourceAwsS3Bucket()},
		TerraformResource{DataSource, "dataSourceAwsS3BucketObject", dataSourceAwsS3BucketObject()},
		TerraformResource{DataSource, "dataSourceAwsSecretsManagerSecret", dataSourceAwsSecretsManagerSecret()}, // dataSourceAwsSecretsmanagerSecret(),
		TerraformResource{DataSource, "dataSourceAwsSecretsManagerSecretVersion", dataSourceAwsSecretsManagerSecretVersion()}, // dataSourceAwsSecretsmanagerSecretVersion(),
		TerraformResource{DataSource, "dataSourceAwsSecurityGroup", dataSourceAwsSecurityGroup()},
		TerraformResource{DataSource, "dataSourceAwsSnsTopic", dataSourceAwsSnsTopic()}, // dataSourceAwsSns(),
		TerraformResource{DataSource, "dataSourceAwsSqsQueue", dataSourceAwsSqsQueue()},
		TerraformResource{DataSource, "dataSourceAwsSsmParameter", dataSourceAwsSsmParameter()},
		TerraformResource{DataSource, "dataSourceAwsSubnet", dataSourceAwsSubnet()},
		TerraformResource{DataSource, "dataSourceAwsSubnetIDs", dataSourceAwsSubnetIDs()}, // dataSourceAwsSubnetIds(),
		TerraformResource{DataSource, "dataSourceAwsVpc", dataSourceAwsVpc()},
		TerraformResource{DataSource, "dataSourceAwsVpcDhcpOptions", dataSourceAwsVpcDhcpOptions()},
		TerraformResource{DataSource, "dataSourceAwsVpcEndpoint", dataSourceAwsVpcEndpoint()},
		TerraformResource{DataSource, "dataSourceAwsVpcEndpointService", dataSourceAwsVpcEndpointService()},
		TerraformResource{DataSource, "dataSourceAwsVpcPeeringConnection", dataSourceAwsVpcPeeringConnection()},
		TerraformResource{DataSource, "dataSourceAwsVpcs", dataSourceAwsVpcs()},
		TerraformResource{DataSource, "dataSourceAwsVpnGateway", dataSourceAwsVpnGateway()},
	}
}

func Resources() []TerraformResource {
	return []TerraformResource{
		TerraformResource{Resource, "resourceAwsAcmCertificate", resourceAwsAcmCertificate()},
		TerraformResource{Resource, "resourceAwsAcmCertificateValidation", resourceAwsAcmCertificateValidation()},
		TerraformResource{Resource, "resourceAwsAcmpcaCertificateAuthority", resourceAwsAcmpcaCertificateAuthority()},
		TerraformResource{Resource, "resourceAwsAmi", resourceAwsAmi()},
		TerraformResource{Resource, "resourceAwsAmiCopy", resourceAwsAmiCopy()},
		TerraformResource{Resource, "resourceAwsAmiFromInstance", resourceAwsAmiFromInstance()},
		TerraformResource{Resource, "resourceAwsAmiLaunchPermission", resourceAwsAmiLaunchPermission()},
		TerraformResource{Resource, "resourceAwsApiGatewayAccount", resourceAwsApiGatewayAccount()},
		TerraformResource{Resource, "resourceAwsApiGatewayApiKey", resourceAwsApiGatewayApiKey()},
		TerraformResource{Resource, "resourceAwsApiGatewayAuthorizer", resourceAwsApiGatewayAuthorizer()},
		TerraformResource{Resource, "resourceAwsApiGatewayBasePathMapping", resourceAwsApiGatewayBasePathMapping()},
		TerraformResource{Resource, "resourceAwsApiGatewayClientCertificate", resourceAwsApiGatewayClientCertificate()},
		TerraformResource{Resource, "resourceAwsApiGatewayDeployment", resourceAwsApiGatewayDeployment()},
		TerraformResource{Resource, "resourceAwsApiGatewayDocumentationPart", resourceAwsApiGatewayDocumentationPart()},
		TerraformResource{Resource, "resourceAwsApiGatewayDocumentationVersion", resourceAwsApiGatewayDocumentationVersion()},
		TerraformResource{Resource, "resourceAwsApiGatewayDomainName", resourceAwsApiGatewayDomainName()},
		TerraformResource{Resource, "resourceAwsApiGatewayGatewayResponse", resourceAwsApiGatewayGatewayResponse()},
		TerraformResource{Resource, "resourceAwsApiGatewayIntegration", resourceAwsApiGatewayIntegration()},
		TerraformResource{Resource, "resourceAwsApiGatewayIntegrationResponse", resourceAwsApiGatewayIntegrationResponse()},
		TerraformResource{Resource, "resourceAwsApiGatewayMethod", resourceAwsApiGatewayMethod()},
		TerraformResource{Resource, "resourceAwsApiGatewayMethodResponse", resourceAwsApiGatewayMethodResponse()},
		TerraformResource{Resource, "resourceAwsApiGatewayMethodSettings", resourceAwsApiGatewayMethodSettings()},
		TerraformResource{Resource, "resourceAwsApiGatewayModel", resourceAwsApiGatewayModel()},
		TerraformResource{Resource, "resourceAwsApiGatewayRequestValidator", resourceAwsApiGatewayRequestValidator()},
		TerraformResource{Resource, "resourceAwsApiGatewayResource", resourceAwsApiGatewayResource()},
		TerraformResource{Resource, "resourceAwsApiGatewayRestApi", resourceAwsApiGatewayRestApi()},
		TerraformResource{Resource, "resourceAwsApiGatewayStage", resourceAwsApiGatewayStage()},
		TerraformResource{Resource, "resourceAwsApiGatewayUsagePlan", resourceAwsApiGatewayUsagePlan()},
		TerraformResource{Resource, "resourceAwsApiGatewayUsagePlanKey", resourceAwsApiGatewayUsagePlanKey()},
		TerraformResource{Resource, "resourceAwsApiGatewayVpcLink", resourceAwsApiGatewayVpcLink()},
		TerraformResource{Resource, "resourceAwsAppCookieStickinessPolicy", resourceAwsAppCookieStickinessPolicy()},
		TerraformResource{Resource, "resourceAwsAppautoscalingPolicy", resourceAwsAppautoscalingPolicy()},
		TerraformResource{Resource, "resourceAwsAppautoscalingScheduledAction", resourceAwsAppautoscalingScheduledAction()},
		TerraformResource{Resource, "resourceAwsAppautoscalingTarget", resourceAwsAppautoscalingTarget()},
		TerraformResource{Resource, "resourceAwsAppsyncDatasource", resourceAwsAppsyncDatasource()},
		TerraformResource{Resource, "resourceAwsAppsyncGraphqlApi", resourceAwsAppsyncGraphqlApi()},
		TerraformResource{Resource, "resourceAwsAthenaDatabase", resourceAwsAthenaDatabase()},
		TerraformResource{Resource, "resourceAwsAthenaNamedQuery", resourceAwsAthenaNamedQuery()},
		TerraformResource{Resource, "resourceAwsAutoscalingAttachment", resourceAwsAutoscalingAttachment()},
		TerraformResource{Resource, "resourceAwsAutoscalingGroup", resourceAwsAutoscalingGroup()},
		// resourceAwsAutoscalingGroupWaiting(),
		TerraformResource{Resource, "resourceAwsAutoscalingLifecycleHook", resourceAwsAutoscalingLifecycleHook()},
		TerraformResource{Resource, "resourceAwsAutoscalingNotification", resourceAwsAutoscalingNotification()},
		TerraformResource{Resource, "resourceAwsAutoscalingPolicy", resourceAwsAutoscalingPolicy()},
		TerraformResource{Resource, "resourceAwsAutoscalingSchedule", resourceAwsAutoscalingSchedule()},
		TerraformResource{Resource, "resourceAwsBatchComputeEnvironment", resourceAwsBatchComputeEnvironment()},
		TerraformResource{Resource, "resourceAwsBatchJobDefinition", resourceAwsBatchJobDefinition()},
		TerraformResource{Resource, "resourceAwsBatchJobQueue", resourceAwsBatchJobQueue()},
		TerraformResource{Resource, "resourceAwsBudgetsBudget", resourceAwsBudgetsBudget()},
		TerraformResource{Resource, "resourceAwsCloud9EnvironmentEc2", resourceAwsCloud9EnvironmentEc2()},
		TerraformResource{Resource, "resourceAwsCloudFormationStack", resourceAwsCloudFormationStack()}, // resourceAwsCloudformationStack(),
		TerraformResource{Resource, "resourceAwsCloudFrontDistribution", resourceAwsCloudFrontDistribution()}, // resourceAwsCloudfrontDistribution(),
		TerraformResource{Resource, "resourceAwsCloudFrontOriginAccessIdentity", resourceAwsCloudFrontOriginAccessIdentity()}, // resourceAwsCloudfrontOriginAccessIdentity(),
		TerraformResource{Resource, "resourceAwsCloudTrail", resourceAwsCloudTrail()}, // resourceAwsCloudtrail(),
		TerraformResource{Resource, "resourceAwsCloudWatchDashboard", resourceAwsCloudWatchDashboard()}, // resourceAwsCloudwatchDashboard(),
		TerraformResource{Resource, "resourceAwsCloudWatchEventPermission", resourceAwsCloudWatchEventPermission()}, // resourceAwsCloudwatchEventPermission(),
		TerraformResource{Resource, "resourceAwsCloudWatchEventRule", resourceAwsCloudWatchEventRule()}, // resourceAwsCloudwatchEventRule(),
		TerraformResource{Resource, "resourceAwsCloudWatchEventTarget", resourceAwsCloudWatchEventTarget()}, // resourceAwsCloudwatchEventTarget(),
		TerraformResource{Resource, "resourceAwsCloudWatchLogDestination", resourceAwsCloudWatchLogDestination()}, // resourceAwsCloudwatchLogDestination(),
		TerraformResource{Resource, "resourceAwsCloudWatchLogDestinationPolicy", resourceAwsCloudWatchLogDestinationPolicy()}, // resourceAwsCloudwatchLogDestinationPolicy(),
		TerraformResource{Resource, "resourceAwsCloudWatchLogGroup", resourceAwsCloudWatchLogGroup()}, // resourceAwsCloudwatchLogGroup(),
		TerraformResource{Resource, "resourceAwsCloudWatchLogMetricFilter", resourceAwsCloudWatchLogMetricFilter()}, // resourceAwsCloudwatchLogMetricFilter(),
		TerraformResource{Resource, "resourceAwsCloudWatchLogResourcePolicy", resourceAwsCloudWatchLogResourcePolicy()}, // resourceAwsCloudwatchLogResourcePolicy(),
		TerraformResource{Resource, "resourceAwsCloudWatchLogStream", resourceAwsCloudWatchLogStream()}, // resourceAwsCloudwatchLogStream(),
		TerraformResource{Resource, "resourceAwsCloudwatchLogSubscriptionFilter", resourceAwsCloudwatchLogSubscriptionFilter()},
		TerraformResource{Resource, "resourceAwsCloudWatchMetricAlarm", resourceAwsCloudWatchMetricAlarm()}, // resourceAwsCloudwatchMetricAlarm(),
		// resourceAwsCloudwatchMetricAlarmMigrate(),
		TerraformResource{Resource, "resourceAwsCodeBuildProject", resourceAwsCodeBuildProject()}, // resourceAwsCodebuildProject(),
		// resourceAwsCodebuildProjectMigrate(),
		TerraformResource{Resource, "resourceAwsCodeBuildWebhook", resourceAwsCodeBuildWebhook()}, // resourceAwsCodebuildWebhook(),
		TerraformResource{Resource, "resourceAwsCodeCommitRepository", resourceAwsCodeCommitRepository()}, // resourceAwsCodecommitRepository(),
		TerraformResource{Resource, "resourceAwsCodeCommitTrigger", resourceAwsCodeCommitTrigger()}, // resourceAwsCodecommitTrigger(),
		TerraformResource{Resource, "resourceAwsCodeDeployApp", resourceAwsCodeDeployApp()}, // resourceAwsCodedeployApp(),
		TerraformResource{Resource, "resourceAwsCodeDeployDeploymentConfig", resourceAwsCodeDeployDeploymentConfig()}, // resourceAwsCodedeployDeploymentConfig(),
		TerraformResource{Resource, "resourceAwsCodeDeployDeploymentGroup", resourceAwsCodeDeployDeploymentGroup()}, // resourceAwsCodedeployDeploymentGroup(),
		TerraformResource{Resource, "resourceAwsCodePipeline", resourceAwsCodePipeline()}, // resourceAwsCodepipeline(),
		TerraformResource{Resource, "resourceAwsCognitoIdentityPool", resourceAwsCognitoIdentityPool()},
		TerraformResource{Resource, "resourceAwsCognitoIdentityPoolRolesAttachment", resourceAwsCognitoIdentityPoolRolesAttachment()},
		TerraformResource{Resource, "resourceAwsCognitoIdentityProvider", resourceAwsCognitoIdentityProvider()},
		TerraformResource{Resource, "resourceAwsCognitoResourceServer", resourceAwsCognitoResourceServer()},
		TerraformResource{Resource, "resourceAwsCognitoUserGroup", resourceAwsCognitoUserGroup()},
		TerraformResource{Resource, "resourceAwsCognitoUserPool", resourceAwsCognitoUserPool()},
		TerraformResource{Resource, "resourceAwsCognitoUserPoolClient", resourceAwsCognitoUserPoolClient()},
		TerraformResource{Resource, "resourceAwsCognitoUserPoolDomain", resourceAwsCognitoUserPoolDomain()},
		TerraformResource{Resource, "resourceAwsConfigAggregateAuthorization", resourceAwsConfigAggregateAuthorization()},
		TerraformResource{Resource, "resourceAwsConfigConfigRule", resourceAwsConfigConfigRule()},
		TerraformResource{Resource, "resourceAwsConfigConfigurationAggregator", resourceAwsConfigConfigurationAggregator()},
		TerraformResource{Resource, "resourceAwsConfigConfigurationRecorder", resourceAwsConfigConfigurationRecorder()},
		TerraformResource{Resource, "resourceAwsConfigConfigurationRecorderStatus", resourceAwsConfigConfigurationRecorderStatus()},
		TerraformResource{Resource, "resourceAwsConfigDeliveryChannel", resourceAwsConfigDeliveryChannel()},
		TerraformResource{Resource, "resourceAwsCustomerGateway", resourceAwsCustomerGateway()},
		TerraformResource{Resource, "resourceAwsDaxCluster", resourceAwsDaxCluster()},
		TerraformResource{Resource, "resourceAwsDaxParameterGroup", resourceAwsDaxParameterGroup()},
		TerraformResource{Resource, "resourceAwsDaxSubnetGroup", resourceAwsDaxSubnetGroup()},
		TerraformResource{Resource, "resourceAwsDbEventSubscription", resourceAwsDbEventSubscription()},
		TerraformResource{Resource, "resourceAwsDbInstance", resourceAwsDbInstance()},
		TerraformResource{Resource, "resourceAwsDbOptionGroup", resourceAwsDbOptionGroup()},
		TerraformResource{Resource, "resourceAwsDbParameterGroup", resourceAwsDbParameterGroup()},
		TerraformResource{Resource, "resourceAwsDbSecurityGroup", resourceAwsDbSecurityGroup()},
		TerraformResource{Resource, "resourceAwsDbSnapshot", resourceAwsDbSnapshot()},
		TerraformResource{Resource, "resourceAwsDbSubnetGroup", resourceAwsDbSubnetGroup()},
		TerraformResource{Resource, "resourceAwsDefaultNetworkAcl", resourceAwsDefaultNetworkAcl()},
		TerraformResource{Resource, "resourceAwsDefaultRouteTable", resourceAwsDefaultRouteTable()},
		TerraformResource{Resource, "resourceAwsDefaultSecurityGroup", resourceAwsDefaultSecurityGroup()},
		TerraformResource{Resource, "resourceAwsDefaultSubnet", resourceAwsDefaultSubnet()},
		TerraformResource{Resource, "resourceAwsDefaultVpc", resourceAwsDefaultVpc()},
		TerraformResource{Resource, "resourceAwsDefaultVpcDhcpOptions", resourceAwsDefaultVpcDhcpOptions()},
		TerraformResource{Resource, "resourceAwsDevicefarmProject", resourceAwsDevicefarmProject()},
		TerraformResource{Resource, "resourceAwsDirectoryServiceConditionalForwarder", resourceAwsDirectoryServiceConditionalForwarder()},
		TerraformResource{Resource, "resourceAwsDirectoryServiceDirectory", resourceAwsDirectoryServiceDirectory()},
		TerraformResource{Resource, "resourceAwsDmsCertificate", resourceAwsDmsCertificate()},
		TerraformResource{Resource, "resourceAwsDmsEndpoint", resourceAwsDmsEndpoint()},
		TerraformResource{Resource, "resourceAwsDmsReplicationInstance", resourceAwsDmsReplicationInstance()},
		TerraformResource{Resource, "resourceAwsDmsReplicationSubnetGroup", resourceAwsDmsReplicationSubnetGroup()},
		TerraformResource{Resource, "resourceAwsDmsReplicationTask", resourceAwsDmsReplicationTask()},
		TerraformResource{Resource, "resourceAwsDxConnection", resourceAwsDxConnection()},
		TerraformResource{Resource, "resourceAwsDxConnectionAssociation", resourceAwsDxConnectionAssociation()},
		TerraformResource{Resource, "resourceAwsDxGateway", resourceAwsDxGateway()},
		TerraformResource{Resource, "resourceAwsDxGatewayAssociation", resourceAwsDxGatewayAssociation()},
		TerraformResource{Resource, "resourceAwsDxLag", resourceAwsDxLag()},
		TerraformResource{Resource, "resourceAwsDynamoDbGlobalTable", resourceAwsDynamoDbGlobalTable()}, // resourceAwsDynamodbGlobalTable(),
		TerraformResource{Resource, "resourceAwsDynamoDbTable", resourceAwsDynamoDbTable()}, // resourceAwsDynamodbTable(),
		TerraformResource{Resource, "resourceAwsDynamoDbTableItem", resourceAwsDynamoDbTableItem()}, // resourceAwsDynamodbTableItem(),
		// resourceAwsDynamodbTableMigrate(),
		TerraformResource{Resource, "resourceAwsEbsSnapshot", resourceAwsEbsSnapshot()},
		TerraformResource{Resource, "resourceAwsEbsVolume", resourceAwsEbsVolume()},
		TerraformResource{Resource, "resourceAwsEcrLifecyclePolicy", resourceAwsEcrLifecyclePolicy()},
		TerraformResource{Resource, "resourceAwsEcrRepository", resourceAwsEcrRepository()},
		TerraformResource{Resource, "resourceAwsEcrRepositoryPolicy", resourceAwsEcrRepositoryPolicy()},
		TerraformResource{Resource, "resourceAwsEcsCluster", resourceAwsEcsCluster()},
		TerraformResource{Resource, "resourceAwsEcsService", resourceAwsEcsService()},
		TerraformResource{Resource, "resourceAwsEcsTaskDefinition", resourceAwsEcsTaskDefinition()},
		// resourceAwsEcsTaskDefinitionMigrate(),
		TerraformResource{Resource, "resourceAwsEfsFileSystem", resourceAwsEfsFileSystem()},
		TerraformResource{Resource, "resourceAwsEfsMountTarget", resourceAwsEfsMountTarget()},
		TerraformResource{Resource, "resourceAwsEgressOnlyInternetGateway", resourceAwsEgressOnlyInternetGateway()},
		TerraformResource{Resource, "resourceAwsEip", resourceAwsEip()},
		TerraformResource{Resource, "resourceAwsEipAssociation", resourceAwsEipAssociation()},
		TerraformResource{Resource, "resourceAwsEksCluster", resourceAwsEksCluster()},
		TerraformResource{Resource, "resourceAwsElasticBeanstalkApplication", resourceAwsElasticBeanstalkApplication()},
		TerraformResource{Resource, "resourceAwsElasticBeanstalkApplicationVersion", resourceAwsElasticBeanstalkApplicationVersion()},
		TerraformResource{Resource, "resourceAwsElasticBeanstalkConfigurationTemplate", resourceAwsElasticBeanstalkConfigurationTemplate()},
		TerraformResource{Resource, "resourceAwsElasticBeanstalkEnvironment", resourceAwsElasticBeanstalkEnvironment()},
		// resourceAwsElasticBeanstalkEnvironmentMigrate(),
		TerraformResource{Resource, "resourceAwsElasticTranscoderPipeline", resourceAwsElasticTranscoderPipeline()},
		TerraformResource{Resource, "resourceAwsElasticTranscoderPreset", resourceAwsElasticTranscoderPreset()},
		TerraformResource{Resource, "resourceAwsElasticacheCluster", resourceAwsElasticacheCluster()},
		TerraformResource{Resource, "resourceAwsElasticacheParameterGroup", resourceAwsElasticacheParameterGroup()},
		TerraformResource{Resource, "resourceAwsElasticacheReplicationGroup", resourceAwsElasticacheReplicationGroup()},
		// resourceAwsElasticacheReplicationGroupMigrate(),
		TerraformResource{Resource, "resourceAwsElasticacheSecurityGroup", resourceAwsElasticacheSecurityGroup()},
		TerraformResource{Resource, "resourceAwsElasticacheSubnetGroup", resourceAwsElasticacheSubnetGroup()},
		TerraformResource{Resource, "resourceAwsElasticSearchDomain", resourceAwsElasticSearchDomain()}, // resourceAwsElasticsearchDomain(),
		TerraformResource{Resource, "resourceAwsElasticSearchDomainPolicy", resourceAwsElasticSearchDomainPolicy()}, // resourceAwsElasticsearchDomainPolicy(),
		TerraformResource{Resource, "resourceAwsElb", resourceAwsElb()},
		TerraformResource{Resource, "resourceAwsElbAttachment", resourceAwsElbAttachment()},
		TerraformResource{Resource, "resourceAwsEMRCluster", resourceAwsEMRCluster()}, // resourceAwsEmrCluster(),
		TerraformResource{Resource, "resourceAwsEMRInstanceGroup", resourceAwsEMRInstanceGroup()}, // resourceAwsEmrInstanceGroup(),
		TerraformResource{Resource, "resourceAwsEMRSecurityConfiguration", resourceAwsEMRSecurityConfiguration()}, // resourceAwsEmrSecurityConfiguration(),
		TerraformResource{Resource, "resourceAwsFlowLog", resourceAwsFlowLog()},
		TerraformResource{Resource, "resourceAwsGameliftAlias", resourceAwsGameliftAlias()},
		TerraformResource{Resource, "resourceAwsGameliftBuild", resourceAwsGameliftBuild()},
		TerraformResource{Resource, "resourceAwsGameliftFleet", resourceAwsGameliftFleet()},
		TerraformResource{Resource, "resourceAwsGlacierVault", resourceAwsGlacierVault()},
		TerraformResource{Resource, "resourceAwsGlueCatalogDatabase", resourceAwsGlueCatalogDatabase()},
		TerraformResource{Resource, "resourceAwsGlueCatalogTable", resourceAwsGlueCatalogTable()},
		TerraformResource{Resource, "resourceAwsGlueClassifier", resourceAwsGlueClassifier()},
		TerraformResource{Resource, "resourceAwsGlueConnection", resourceAwsGlueConnection()},
		TerraformResource{Resource, "resourceAwsGlueCrawler", resourceAwsGlueCrawler()},
		TerraformResource{Resource, "resourceAwsGlueJob", resourceAwsGlueJob()},
		TerraformResource{Resource, "resourceAwsGlueTrigger", resourceAwsGlueTrigger()},
		TerraformResource{Resource, "resourceAwsGuardDutyDetector", resourceAwsGuardDutyDetector()}, // resourceAwsGuarddutyDetector(),
		TerraformResource{Resource, "resourceAwsGuardDutyIpset", resourceAwsGuardDutyIpset()}, // resourceAwsGuarddutyIpset(),
		TerraformResource{Resource, "resourceAwsGuardDutyMember", resourceAwsGuardDutyMember()}, // resourceAwsGuarddutyMember(),
		TerraformResource{Resource, "resourceAwsGuardDutyThreatintelset", resourceAwsGuardDutyThreatintelset()}, // resourceAwsGuarddutyThreatintelset(),
		TerraformResource{Resource, "resourceAwsIamAccessKey", resourceAwsIamAccessKey()},
		TerraformResource{Resource, "resourceAwsIamAccountAlias", resourceAwsIamAccountAlias()},
		TerraformResource{Resource, "resourceAwsIamAccountPasswordPolicy", resourceAwsIamAccountPasswordPolicy()},
		TerraformResource{Resource, "resourceAwsIamGroup", resourceAwsIamGroup()},
		TerraformResource{Resource, "resourceAwsIamGroupMembership", resourceAwsIamGroupMembership()},
		TerraformResource{Resource, "resourceAwsIamGroupPolicy", resourceAwsIamGroupPolicy()},
		TerraformResource{Resource, "resourceAwsIamGroupPolicyAttachment", resourceAwsIamGroupPolicyAttachment()},
		TerraformResource{Resource, "resourceAwsIamInstanceProfile", resourceAwsIamInstanceProfile()},
		TerraformResource{Resource, "resourceAwsIamOpenIDConnectProvider", resourceAwsIamOpenIDConnectProvider()}, // resourceAwsIamOpenidConnectProvider(),
		TerraformResource{Resource, "resourceAwsIamPolicy", resourceAwsIamPolicy()},
		TerraformResource{Resource, "resourceAwsIamPolicyAttachment", resourceAwsIamPolicyAttachment()},
		TerraformResource{Resource, "resourceAwsIamRole", resourceAwsIamRole()},
		TerraformResource{Resource, "resourceAwsIamRolePolicy", resourceAwsIamRolePolicy()},
		TerraformResource{Resource, "resourceAwsIamRolePolicyAttachment", resourceAwsIamRolePolicyAttachment()},
		TerraformResource{Resource, "resourceAwsIamSamlProvider", resourceAwsIamSamlProvider()},
		TerraformResource{Resource, "resourceAwsIAMServerCertificate", resourceAwsIAMServerCertificate()}, // resourceAwsIamServerCertificate(),
		TerraformResource{Resource, "resourceAwsIamServiceLinkedRole", resourceAwsIamServiceLinkedRole()},
		TerraformResource{Resource, "resourceAwsIamUser", resourceAwsIamUser()},
		TerraformResource{Resource, "resourceAwsIamUserGroupMembership", resourceAwsIamUserGroupMembership()},
		TerraformResource{Resource, "resourceAwsIamUserLoginProfile", resourceAwsIamUserLoginProfile()},
		TerraformResource{Resource, "resourceAwsIamUserPolicy", resourceAwsIamUserPolicy()},
		TerraformResource{Resource, "resourceAwsIamUserPolicyAttachment", resourceAwsIamUserPolicyAttachment()},
		TerraformResource{Resource, "resourceAwsIamUserSshKey", resourceAwsIamUserSshKey()},
		TerraformResource{Resource, "resourceAWSInspectorAssessmentTarget", resourceAWSInspectorAssessmentTarget()}, // resourceAwsInspectorAssessmentTarget(),
		TerraformResource{Resource, "resourceAWSInspectorAssessmentTemplate", resourceAWSInspectorAssessmentTemplate()}, // resourceAwsInspectorAssessmentTemplate(),
		TerraformResource{Resource, "resourceAWSInspectorResourceGroup", resourceAWSInspectorResourceGroup()}, // resourceAwsInspectorResourceGroup(),
		TerraformResource{Resource, "resourceAwsInstance", resourceAwsInstance()},
		// resourceAwsInstanceMigrate(),
		TerraformResource{Resource, "resourceAwsInternetGateway", resourceAwsInternetGateway()},
		TerraformResource{Resource, "resourceAwsIotCertificate", resourceAwsIotCertificate()},
		TerraformResource{Resource, "resourceAwsIotPolicy", resourceAwsIotPolicy()},
		TerraformResource{Resource, "resourceAwsIotThing", resourceAwsIotThing()},
		TerraformResource{Resource, "resourceAwsIotThingType", resourceAwsIotThingType()},
		TerraformResource{Resource, "resourceAwsIotTopicRule", resourceAwsIotTopicRule()},
		TerraformResource{Resource, "resourceAwsKeyPair", resourceAwsKeyPair()},
		// resourceAwsKeyPairMigrate(),
		TerraformResource{Resource, "resourceAwsKinesisFirehoseDeliveryStream", resourceAwsKinesisFirehoseDeliveryStream()},
		// resourceAwsKinesisFirehoseDeliveryStreamMigrate(),
		TerraformResource{Resource, "resourceAwsKinesisStream", resourceAwsKinesisStream()},
		TerraformResource{Resource, "resourceAwsKmsAlias", resourceAwsKmsAlias()},
		TerraformResource{Resource, "resourceAwsKmsGrant", resourceAwsKmsGrant()},
		TerraformResource{Resource, "resourceAwsKmsKey", resourceAwsKmsKey()},
		TerraformResource{Resource, "resourceAwsLambdaAlias", resourceAwsLambdaAlias()},
		TerraformResource{Resource, "resourceAwsLambdaEventSourceMapping", resourceAwsLambdaEventSourceMapping()},
		TerraformResource{Resource, "resourceAwsLambdaFunction", resourceAwsLambdaFunction()},
		TerraformResource{Resource, "resourceAwsLambdaPermission", resourceAwsLambdaPermission()},
		TerraformResource{Resource, "resourceAwsLaunchConfiguration", resourceAwsLaunchConfiguration()},
		TerraformResource{Resource, "resourceAwsLaunchTemplate", resourceAwsLaunchTemplate()},
		TerraformResource{Resource, "resourceAwsLb", resourceAwsLb()},
		TerraformResource{Resource, "resourceAwsLBCookieStickinessPolicy", resourceAwsLBCookieStickinessPolicy()}, // resourceAwsLbCookieStickinessPolicy(),
		TerraformResource{Resource, "resourceAwsLbListener", resourceAwsLbListener()},
		TerraformResource{Resource, "resourceAwsLbListenerCertificate", resourceAwsLbListenerCertificate()},
		TerraformResource{Resource, "resourceAwsLbbListenerRule", resourceAwsLbbListenerRule()}, // resourceAwsLbListenerRule(),
		TerraformResource{Resource, "resourceAwsLBSSLNegotiationPolicy", resourceAwsLBSSLNegotiationPolicy()}, // resourceAwsLbSslNegotiationPolicy(),
		TerraformResource{Resource, "resourceAwsLbTargetGroup", resourceAwsLbTargetGroup()},
		TerraformResource{Resource, "resourceAwsLbTargetGroupAttachment", resourceAwsLbTargetGroupAttachment()},
		TerraformResource{Resource, "resourceAwsLightsailDomain", resourceAwsLightsailDomain()},
		TerraformResource{Resource, "resourceAwsLightsailInstance", resourceAwsLightsailInstance()},
		TerraformResource{Resource, "resourceAwsLightsailKeyPair", resourceAwsLightsailKeyPair()},
		TerraformResource{Resource, "resourceAwsLightsailStaticIp", resourceAwsLightsailStaticIp()},
		TerraformResource{Resource, "resourceAwsLightsailStaticIpAttachment", resourceAwsLightsailStaticIpAttachment()},
		TerraformResource{Resource, "resourceAwsLoadBalancerBackendServerPolicies", resourceAwsLoadBalancerBackendServerPolicies()}, // resourceAwsLoadBalancerBackendServerPolicy(),
		TerraformResource{Resource, "resourceAwsLoadBalancerListenerPolicies", resourceAwsLoadBalancerListenerPolicies()}, // resourceAwsLoadBalancerListenerPolicy(),
		TerraformResource{Resource, "resourceAwsLoadBalancerPolicy", resourceAwsLoadBalancerPolicy()},
		TerraformResource{Resource, "resourceAwsMainRouteTableAssociation", resourceAwsMainRouteTableAssociation()},
		TerraformResource{Resource, "resourceAwsMediaStoreContainer", resourceAwsMediaStoreContainer()},
		TerraformResource{Resource, "resourceAwsMqBroker", resourceAwsMqBroker()},
		TerraformResource{Resource, "resourceAwsMqConfiguration", resourceAwsMqConfiguration()},
		TerraformResource{Resource, "resourceAwsNatGateway", resourceAwsNatGateway()},
		TerraformResource{Resource, "resourceAwsNeptuneClusterParameterGroup", resourceAwsNeptuneClusterParameterGroup()},
		TerraformResource{Resource, "resourceAwsNeptuneParameterGroup", resourceAwsNeptuneParameterGroup()},
		TerraformResource{Resource, "resourceAwsNeptuneSubnetGroup", resourceAwsNeptuneSubnetGroup()},
		TerraformResource{Resource, "resourceAwsNetworkAcl", resourceAwsNetworkAcl()},
		TerraformResource{Resource, "resourceAwsNetworkAclRule", resourceAwsNetworkAclRule()},
		TerraformResource{Resource, "resourceAwsNetworkInterface", resourceAwsNetworkInterface()},
		TerraformResource{Resource, "resourceAwsNetworkInterfaceAttachment", resourceAwsNetworkInterfaceAttachment()},
		TerraformResource{Resource, "resourceAwsNetworkInterfaceSGAttachment", resourceAwsNetworkInterfaceSGAttachment()}, // resourceAwsNetworkInterfaceSgAttachment(),
		TerraformResource{Resource, "resourceAwsOpsworksApplication", resourceAwsOpsworksApplication()},
		TerraformResource{Resource, "resourceAwsOpsworksCustomLayer", resourceAwsOpsworksCustomLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksGangliaLayer", resourceAwsOpsworksGangliaLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksHaproxyLayer", resourceAwsOpsworksHaproxyLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksInstance", resourceAwsOpsworksInstance()},
		TerraformResource{Resource, "resourceAwsOpsworksJavaAppLayer", resourceAwsOpsworksJavaAppLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksMemcachedLayer", resourceAwsOpsworksMemcachedLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksMysqlLayer", resourceAwsOpsworksMysqlLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksNodejsAppLayer", resourceAwsOpsworksNodejsAppLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksPermission", resourceAwsOpsworksPermission()},
		TerraformResource{Resource, "resourceAwsOpsworksPhpAppLayer", resourceAwsOpsworksPhpAppLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksRailsAppLayer", resourceAwsOpsworksRailsAppLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksRdsDbInstance", resourceAwsOpsworksRdsDbInstance()},
		TerraformResource{Resource, "resourceAwsOpsworksStack", resourceAwsOpsworksStack()},
		TerraformResource{Resource, "resourceAwsOpsworksStaticWebLayer", resourceAwsOpsworksStaticWebLayer()},
		TerraformResource{Resource, "resourceAwsOpsworksUserProfile", resourceAwsOpsworksUserProfile()},
		TerraformResource{Resource, "resourceAwsOrganizationsAccount", resourceAwsOrganizationsAccount()},
		TerraformResource{Resource, "resourceAwsOrganizationsOrganization", resourceAwsOrganizationsOrganization()},
		TerraformResource{Resource, "resourceAwsOrganizationsPolicy", resourceAwsOrganizationsPolicy()},
		TerraformResource{Resource, "resourceAwsOrganizationsPolicyAttachment", resourceAwsOrganizationsPolicyAttachment()},
		TerraformResource{Resource, "resourceAwsPlacementGroup", resourceAwsPlacementGroup()},
		TerraformResource{Resource, "resourceAwsProxyProtocolPolicy", resourceAwsProxyProtocolPolicy()},
		TerraformResource{Resource, "resourceAwsRDSCluster", resourceAwsRDSCluster()}, // resourceAwsRdsCluster(),
		TerraformResource{Resource, "resourceAwsRDSClusterInstance", resourceAwsRDSClusterInstance()}, // resourceAwsRdsClusterInstance(),
		TerraformResource{Resource, "resourceAwsRDSClusterParameterGroup", resourceAwsRDSClusterParameterGroup()}, // resourceAwsRdsClusterParameterGroup(),
		TerraformResource{Resource, "resourceAwsRedshiftCluster", resourceAwsRedshiftCluster()},
		TerraformResource{Resource, "resourceAwsRedshiftParameterGroup", resourceAwsRedshiftParameterGroup()},
		TerraformResource{Resource, "resourceAwsRedshiftSecurityGroup", resourceAwsRedshiftSecurityGroup()},
		TerraformResource{Resource, "resourceAwsRedshiftSubnetGroup", resourceAwsRedshiftSubnetGroup()},
		TerraformResource{Resource, "resourceAwsRoute", resourceAwsRoute()},
		TerraformResource{Resource, "resourceAwsRoute53DelegationSet", resourceAwsRoute53DelegationSet()},
		TerraformResource{Resource, "resourceAwsRoute53HealthCheck", resourceAwsRoute53HealthCheck()},
		TerraformResource{Resource, "resourceAwsRoute53QueryLog", resourceAwsRoute53QueryLog()},
		TerraformResource{Resource, "resourceAwsRoute53Record", resourceAwsRoute53Record()},
		// resourceAwsRoute53RecordMigrate(),
		TerraformResource{Resource, "resourceAwsRoute53Zone", resourceAwsRoute53Zone()},
		TerraformResource{Resource, "resourceAwsRoute53ZoneAssociation", resourceAwsRoute53ZoneAssociation()},
		TerraformResource{Resource, "resourceAwsRouteTable", resourceAwsRouteTable()},
		TerraformResource{Resource, "resourceAwsRouteTableAssociation", resourceAwsRouteTableAssociation()},
		TerraformResource{Resource, "resourceAwsS3Bucket", resourceAwsS3Bucket()},
		TerraformResource{Resource, "resourceAwsS3BucketMetric", resourceAwsS3BucketMetric()},
		TerraformResource{Resource, "resourceAwsS3BucketNotification", resourceAwsS3BucketNotification()},
		TerraformResource{Resource, "resourceAwsS3BucketObject", resourceAwsS3BucketObject()},
		TerraformResource{Resource, "resourceAwsS3BucketPolicy", resourceAwsS3BucketPolicy()},
		TerraformResource{Resource, "resourceAwsSecretsManagerSecret", resourceAwsSecretsManagerSecret()}, // resourceAwsSecretsmanagerSecret(),
		TerraformResource{Resource, "resourceAwsSecretsManagerSecretVersion", resourceAwsSecretsManagerSecretVersion()}, // resourceAwsSecretsmanagerSecretVersion(),
		TerraformResource{Resource, "resourceAwsSecurityGroup", resourceAwsSecurityGroup()},
		// resourceAwsSecurityGroupMigrate(),
		TerraformResource{Resource, "resourceAwsSecurityGroupRule", resourceAwsSecurityGroupRule()},
		// resourceAwsSecurityGroupRuleMigrate(),
		TerraformResource{Resource, "resourceAwsServiceDiscoveryPrivateDnsNamespace", resourceAwsServiceDiscoveryPrivateDnsNamespace()},
		TerraformResource{Resource, "resourceAwsServiceDiscoveryPublicDnsNamespace", resourceAwsServiceDiscoveryPublicDnsNamespace()},
		TerraformResource{Resource, "resourceAwsServiceDiscoveryService", resourceAwsServiceDiscoveryService()},
		// resourceAwsServiceDiscoveryServiceMigrate(),
		TerraformResource{Resource, "resourceAwsServiceCatalogPortfolio", resourceAwsServiceCatalogPortfolio()}, // resourceAwsServicecatalogPortfolio(),
		TerraformResource{Resource, "resourceAwsSesActiveReceiptRuleSet", resourceAwsSesActiveReceiptRuleSet()},
		TerraformResource{Resource, "resourceAwsSesConfigurationSet", resourceAwsSesConfigurationSet()},
		TerraformResource{Resource, "resourceAwsSesDomainDkim", resourceAwsSesDomainDkim()},
		TerraformResource{Resource, "resourceAwsSesDomainIdentity", resourceAwsSesDomainIdentity()},
		TerraformResource{Resource, "resourceAwsSesDomainIdentityVerification", resourceAwsSesDomainIdentityVerification()},
		TerraformResource{Resource, "resourceAwsSesDomainMailFrom", resourceAwsSesDomainMailFrom()},
		TerraformResource{Resource, "resourceAwsSesEventDestination", resourceAwsSesEventDestination()},
		TerraformResource{Resource, "resourceAwsSesNotificationTopic", resourceAwsSesNotificationTopic()}, // resourceAwsSesIdentityNotificationTopic(),
		TerraformResource{Resource, "resourceAwsSesReceiptFilter", resourceAwsSesReceiptFilter()},
		TerraformResource{Resource, "resourceAwsSesReceiptRule", resourceAwsSesReceiptRule()},
		TerraformResource{Resource, "resourceAwsSesReceiptRuleSet", resourceAwsSesReceiptRuleSet()},
		TerraformResource{Resource, "resourceAwsSesTemplate", resourceAwsSesTemplate()},
		TerraformResource{Resource, "resourceAwsSfnActivity", resourceAwsSfnActivity()},
		TerraformResource{Resource, "resourceAwsSfnStateMachine", resourceAwsSfnStateMachine()},
		TerraformResource{Resource, "resourceAwsSimpleDBDomain", resourceAwsSimpleDBDomain()}, // resourceAwsSimpledbDomain(),
		TerraformResource{Resource, "resourceAwsSnapshotCreateVolumePermission", resourceAwsSnapshotCreateVolumePermission()},
		TerraformResource{Resource, "resourceAwsSnsPlatformApplication", resourceAwsSnsPlatformApplication()},
		TerraformResource{Resource, "resourceAwsSnsSmsPreferences", resourceAwsSnsSmsPreferences()},
		TerraformResource{Resource, "resourceAwsSnsTopic", resourceAwsSnsTopic()},
		TerraformResource{Resource, "resourceAwsSnsTopicPolicy", resourceAwsSnsTopicPolicy()},
		TerraformResource{Resource, "resourceAwsSnsTopicSubscription", resourceAwsSnsTopicSubscription()},
		TerraformResource{Resource, "resourceAwsSpotDataFeedSubscription", resourceAwsSpotDataFeedSubscription()}, // resourceAwsSpotDatafeedSubscription(),
		TerraformResource{Resource, "resourceAwsSpotFleetRequest", resourceAwsSpotFleetRequest()},
		// resourceAwsSpotFleetRequestMigrate(),
		TerraformResource{Resource, "resourceAwsSpotInstanceRequest", resourceAwsSpotInstanceRequest()},
		TerraformResource{Resource, "resourceAwsSqsQueue", resourceAwsSqsQueue()},
		TerraformResource{Resource, "resourceAwsSqsQueuePolicy", resourceAwsSqsQueuePolicy()},
		// resourceAwsSqsQueuePolicyMigrate(),
		TerraformResource{Resource, "resourceAwsSsmActivation", resourceAwsSsmActivation()},
		TerraformResource{Resource, "resourceAwsSsmAssociation", resourceAwsSsmAssociation()},
		// resourceAwsSsmAssociationMigrate(),
		TerraformResource{Resource, "resourceAwsSsmDocument", resourceAwsSsmDocument()},
		TerraformResource{Resource, "resourceAwsSsmMaintenanceWindow", resourceAwsSsmMaintenanceWindow()},
		TerraformResource{Resource, "resourceAwsSsmMaintenanceWindowTarget", resourceAwsSsmMaintenanceWindowTarget()},
		TerraformResource{Resource, "resourceAwsSsmMaintenanceWindowTask", resourceAwsSsmMaintenanceWindowTask()},
		TerraformResource{Resource, "resourceAwsSsmParameter", resourceAwsSsmParameter()},
		TerraformResource{Resource, "resourceAwsSsmPatchBaseline", resourceAwsSsmPatchBaseline()},
		TerraformResource{Resource, "resourceAwsSsmPatchGroup", resourceAwsSsmPatchGroup()},
		TerraformResource{Resource, "resourceAwsSsmResourceDataSync", resourceAwsSsmResourceDataSync()},
		TerraformResource{Resource, "resourceAwsSubnet", resourceAwsSubnet()},
		// resourceAwsSubnetMigrate(),
		TerraformResource{Resource, "resourceAwsVolumeAttachment", resourceAwsVolumeAttachment()},
		TerraformResource{Resource, "resourceAwsVpc", resourceAwsVpc()},
		TerraformResource{Resource, "resourceAwsVpcDhcpOptions", resourceAwsVpcDhcpOptions()},
		TerraformResource{Resource, "resourceAwsVpcDhcpOptionsAssociation", resourceAwsVpcDhcpOptionsAssociation()},
		TerraformResource{Resource, "resourceAwsVpcEndpoint", resourceAwsVpcEndpoint()},
		TerraformResource{Resource, "resourceAwsVpcEndpointConnectionNotification", resourceAwsVpcEndpointConnectionNotification()},
		TerraformResource{Resource, "resourceAwsVpcEndpointRouteTableAssociation", resourceAwsVpcEndpointRouteTableAssociation()},
		TerraformResource{Resource, "resourceAwsVpcEndpointService", resourceAwsVpcEndpointService()},
		TerraformResource{Resource, "resourceAwsVpcEndpointServiceAllowedPrincipal", resourceAwsVpcEndpointServiceAllowedPrincipal()},
		TerraformResource{Resource, "resourceAwsVpcEndpointSubnetAssociation", resourceAwsVpcEndpointSubnetAssociation()},
		// resourceAwsVpcMigrate(),
		TerraformResource{Resource, "resourceAwsVpcPeeringConnection", resourceAwsVpcPeeringConnection()},
		TerraformResource{Resource, "resourceAwsVpcPeeringConnectionAccepter", resourceAwsVpcPeeringConnectionAccepter()},
		TerraformResource{Resource, "resourceAwsVpcPeeringConnectionOptions", resourceAwsVpcPeeringConnectionOptions()},
		TerraformResource{Resource, "resourceAwsVpnConnection", resourceAwsVpnConnection()},
		TerraformResource{Resource, "resourceAwsVpnConnectionRoute", resourceAwsVpnConnectionRoute()},
		TerraformResource{Resource, "resourceAwsVpnGateway", resourceAwsVpnGateway()},
		TerraformResource{Resource, "resourceAwsVpnGatewayAttachment", resourceAwsVpnGatewayAttachment()},
		TerraformResource{Resource, "resourceAwsVpnGatewayRoutePropagation", resourceAwsVpnGatewayRoutePropagation()},
		TerraformResource{Resource, "resourceAwsWafByteMatchSet", resourceAwsWafByteMatchSet()},
		TerraformResource{Resource, "resourceAwsWafGeoMatchSet", resourceAwsWafGeoMatchSet()},
		TerraformResource{Resource, "resourceAwsWafIPSet", resourceAwsWafIPSet()}, // resourceAwsWafIpset(),
		TerraformResource{Resource, "resourceAwsWafRateBasedRule", resourceAwsWafRateBasedRule()},
		TerraformResource{Resource, "resourceAwsWafRegexMatchSet", resourceAwsWafRegexMatchSet()},
		TerraformResource{Resource, "resourceAwsWafRegexPatternSet", resourceAwsWafRegexPatternSet()},
		TerraformResource{Resource, "resourceAwsWafRule", resourceAwsWafRule()},
		TerraformResource{Resource, "resourceAwsWafRuleGroup", resourceAwsWafRuleGroup()},
		TerraformResource{Resource, "resourceAwsWafSizeConstraintSet", resourceAwsWafSizeConstraintSet()},
		TerraformResource{Resource, "resourceAwsWafSqlInjectionMatchSet", resourceAwsWafSqlInjectionMatchSet()},
		TerraformResource{Resource, "resourceAwsWafWebAcl", resourceAwsWafWebAcl()},
		TerraformResource{Resource, "resourceAwsWafXssMatchSet", resourceAwsWafXssMatchSet()},
		TerraformResource{Resource, "resourceAwsWafRegionalByteMatchSet", resourceAwsWafRegionalByteMatchSet()}, // resourceAwsWafregionalByteMatchSet(),
		TerraformResource{Resource, "resourceAwsWafRegionalGeoMatchSet", resourceAwsWafRegionalGeoMatchSet()}, // resourceAwsWafregionalGeoMatchSet(),
		TerraformResource{Resource, "resourceAwsWafRegionalIPSet", resourceAwsWafRegionalIPSet()}, // resourceAwsWafregionalIpset(),
		TerraformResource{Resource, "resourceAwsWafRegionalRateBasedRule", resourceAwsWafRegionalRateBasedRule()}, // resourceAwsWafregionalRateBasedRule(),
		TerraformResource{Resource, "resourceAwsWafRegionalRegexMatchSet", resourceAwsWafRegionalRegexMatchSet()}, // resourceAwsWafregionalRegexMatchSet(),
		TerraformResource{Resource, "resourceAwsWafRegionalRegexPatternSet", resourceAwsWafRegionalRegexPatternSet()}, // resourceAwsWafregionalRegexPatternSet(),
		TerraformResource{Resource, "resourceAwsWafRegionalRule", resourceAwsWafRegionalRule()}, // resourceAwsWafregionalRule(),
		TerraformResource{Resource, "resourceAwsWafRegionalRuleGroup", resourceAwsWafRegionalRuleGroup()}, // resourceAwsWafregionalRuleGroup(),
		TerraformResource{Resource, "resourceAwsWafRegionalSizeConstraintSet", resourceAwsWafRegionalSizeConstraintSet()}, // resourceAwsWafregionalSizeConstraintSet(),
		TerraformResource{Resource, "resourceAwsWafRegionalSqlInjectionMatchSet", resourceAwsWafRegionalSqlInjectionMatchSet()}, // resourceAwsWafregionalSqlInjectionMatchSet(),
		TerraformResource{Resource, "resourceAwsWafRegionalWebAcl", resourceAwsWafRegionalWebAcl()}, // resourceAwsWafregionalWebAcl(),
		TerraformResource{Resource, "resourceAwsWafRegionalWebAclAssociation", resourceAwsWafRegionalWebAclAssociation()}, // resourceAwsWafregionalWebAclAssociation(),
		TerraformResource{Resource, "resourceAwsWafRegionalXssMatchSet", resourceAwsWafRegionalXssMatchSet()}, // resourceAwsWafregionalXssMatchSet(),
	}
}
