package aws

import "github.com/hashicorp/terraform/helper/schema"

type TerraformResourceType int

const (
	DataSource TerraformResourceType = iota
	Resource
)

type TerraformResource struct {
	Type  TerraformResourceType
	Name  string
	Value *schema.Resource
}

func DataSources() []TerraformResource {
	return []TerraformResource{
		{DataSource, "dataSourceAwsAcmCertificate", dataSourceAwsAcmCertificate()},
		{DataSource, "dataSourceAwsAcmpcaCertificateAuthority", dataSourceAwsAcmpcaCertificateAuthority()},
		{DataSource, "dataSourceAwsAmi", dataSourceAwsAmi()},
		{DataSource, "dataSourceAwsAmiIds", dataSourceAwsAmiIds()},
		{DataSource, "dataSourceAwsApiGatewayRestApi", dataSourceAwsApiGatewayRestApi()},
		{DataSource, "dataSourceAwsArn", dataSourceAwsArn()},
		{DataSource, "dataSourceAwsAutoscalingGroups", dataSourceAwsAutoscalingGroups()},
		{DataSource, "dataSourceAwsAvailabilityZone", dataSourceAwsAvailabilityZone()},
		{DataSource, "dataSourceAwsAvailabilityZones", dataSourceAwsAvailabilityZones()},
		{DataSource, "dataSourceAwsBatchComputeEnvironment", dataSourceAwsBatchComputeEnvironment()},
		{DataSource, "dataSourceAwsBatchJobQueue", dataSourceAwsBatchJobQueue()},
		{DataSource, "dataSourceAwsBillingServiceAccount", dataSourceAwsBillingServiceAccount()},
		{DataSource, "dataSourceAwsCallerIdentity", dataSourceAwsCallerIdentity()},
		{DataSource, "dataSourceAwsCanonicalUserId", dataSourceAwsCanonicalUserId()},
		{DataSource, "dataSourceAwsCloudFormationExport", dataSourceAwsCloudFormationExport()},         // dataSourceAwsCloudformationExport(),
		{DataSource, "dataSourceAwsCloudFormationStack", dataSourceAwsCloudFormationStack()},           // dataSourceAwsCloudformationStack(),
		{DataSource, "dataSourceAwsCloudTrailServiceAccount", dataSourceAwsCloudTrailServiceAccount()}, // dataSourceAwsCloudtrailServiceAccount(),
		{DataSource, "dataSourceAwsCloudwatchLogGroup", dataSourceAwsCloudwatchLogGroup()},
		{DataSource, "dataSourceAwsCognitoUserPools", dataSourceAwsCognitoUserPools()},
		// dataSourceAwsCommonSchema(),
		{DataSource, "dataSourceAwsDbInstance", dataSourceAwsDbInstance()},
		{DataSource, "dataSourceAwsDbSnapshot", dataSourceAwsDbSnapshot()},
		{DataSource, "dataSourceAwsDynamoDbTable", dataSourceAwsDynamoDbTable()}, // dataSourceAwsDynamodbTable(),
		{DataSource, "dataSourceAwsEbsSnapshot", dataSourceAwsEbsSnapshot()},
		{DataSource, "dataSourceAwsEbsSnapshotIds", dataSourceAwsEbsSnapshotIds()},
		{DataSource, "dataSourceAwsEbsVolume", dataSourceAwsEbsVolume()},
		{DataSource, "dataSourceAwsEcrRepository", dataSourceAwsEcrRepository()},
		{DataSource, "dataSourceAwsEcsCluster", dataSourceAwsEcsCluster()},
		{DataSource, "dataSourceAwsEcsContainerDefinition", dataSourceAwsEcsContainerDefinition()},
		{DataSource, "dataSourceAwsEcsService", dataSourceAwsEcsService()},
		{DataSource, "dataSourceAwsEcsTaskDefinition", dataSourceAwsEcsTaskDefinition()},
		{DataSource, "dataSourceAwsEfsFileSystem", dataSourceAwsEfsFileSystem()},
		{DataSource, "dataSourceAwsEfsMountTarget", dataSourceAwsEfsMountTarget()},
		{DataSource, "dataSourceAwsEip", dataSourceAwsEip()},
		{DataSource, "dataSourceAwsEksCluster", dataSourceAwsEksCluster()},
		{DataSource, "dataSourceAwsElasticBeanstalkHostedZone", dataSourceAwsElasticBeanstalkHostedZone()},
		{DataSource, "dataSourceAwsElasticBeanstalkSolutionStack", dataSourceAwsElasticBeanstalkSolutionStack()},
		{DataSource, "dataSourceAwsElastiCacheCluster", dataSourceAwsElastiCacheCluster()}, // dataSourceAwsElasticacheCluster(),
		{DataSource, "dataSourceAwsElasticacheReplicationGroup", dataSourceAwsElasticacheReplicationGroup()},
		{DataSource, "dataSourceAwsElb", dataSourceAwsElb()},
		{DataSource, "dataSourceAwsElbHostedZoneId", dataSourceAwsElbHostedZoneId()},
		{DataSource, "dataSourceAwsElbServiceAccount", dataSourceAwsElbServiceAccount()},
		{DataSource, "dataSourceAwsGlueScript", dataSourceAwsGlueScript()},
		{DataSource, "dataSourceAwsIamAccountAlias", dataSourceAwsIamAccountAlias()},
		{DataSource, "dataSourceAwsIAMGroup", dataSourceAwsIAMGroup()},                     // dataSourceAwsIamGroup(),
		{DataSource, "dataSourceAwsIAMInstanceProfile", dataSourceAwsIAMInstanceProfile()}, // dataSourceAwsIamInstanceProfile(),
		{DataSource, "dataSourceAwsIAMPolicy", dataSourceAwsIAMPolicy()},                   // dataSourceAwsIamPolicy(),
		{DataSource, "dataSourceAwsIamPolicyDocument", dataSourceAwsIamPolicyDocument()},
		{DataSource, "dataSourceAwsIAMRole", dataSourceAwsIAMRole()},                           // dataSourceAwsIamRole(),
		{DataSource, "dataSourceAwsIAMServerCertificate", dataSourceAwsIAMServerCertificate()}, // dataSourceAwsIamServerCertificate(),
		{DataSource, "dataSourceAwsIAMUser", dataSourceAwsIAMUser()},                           // dataSourceAwsIamUser(),
		{DataSource, "dataSourceAwsInspectorRulesPackages", dataSourceAwsInspectorRulesPackages()},
		{DataSource, "dataSourceAwsInstance", dataSourceAwsInstance()},
		{DataSource, "dataSourceAwsInstances", dataSourceAwsInstances()},
		{DataSource, "dataSourceAwsInternetGateway", dataSourceAwsInternetGateway()},
		{DataSource, "dataSourceAwsIotEndpoint", dataSourceAwsIotEndpoint()},
		{DataSource, "dataSourceAwsIPRanges", dataSourceAwsIPRanges()}, // dataSourceAwsIpRanges(),
		{DataSource, "dataSourceAwsKinesisStream", dataSourceAwsKinesisStream()},
		{DataSource, "dataSourceAwsKmsAlias", dataSourceAwsKmsAlias()},
		{DataSource, "dataSourceAwsKmsCiphertext", dataSourceAwsKmsCiphertext()},
		{DataSource, "dataSourceAwsKmsKey", dataSourceAwsKmsKey()},
		{DataSource, "dataSourceAwsKmsSecret", dataSourceAwsKmsSecret()},
		{DataSource, "dataSourceAwsLambdaFunction", dataSourceAwsLambdaFunction()},
		{DataSource, "dataSourceAwsLambdaInvocation", dataSourceAwsLambdaInvocation()},
		{DataSource, "dataSourceAwsLb", dataSourceAwsLb()},
		{DataSource, "dataSourceAwsLbListener", dataSourceAwsLbListener()},
		{DataSource, "dataSourceAwsLbTargetGroup", dataSourceAwsLbTargetGroup()},
		{DataSource, "dataSourceAwsMqBroker", dataSourceAwsMqBroker()},
		{DataSource, "dataSourceAwsNatGateway", dataSourceAwsNatGateway()},
		{DataSource, "dataSourceAwsNetworkInterface", dataSourceAwsNetworkInterface()},
		{DataSource, "dataSourceAwsPartition", dataSourceAwsPartition()},
		{DataSource, "dataSourceAwsPrefixList", dataSourceAwsPrefixList()},
		{DataSource, "dataSourceAwsRdsCluster", dataSourceAwsRdsCluster()},
		{DataSource, "dataSourceAwsRedshiftCluster", dataSourceAwsRedshiftCluster()},
		{DataSource, "dataSourceAwsRedshiftServiceAccount", dataSourceAwsRedshiftServiceAccount()},
		{DataSource, "dataSourceAwsRegion", dataSourceAwsRegion()},
		{DataSource, "dataSourceAwsRoute", dataSourceAwsRoute()},
		{DataSource, "dataSourceAwsRoute53Zone", dataSourceAwsRoute53Zone()},
		{DataSource, "dataSourceAwsRouteTable", dataSourceAwsRouteTable()},
		{DataSource, "dataSourceAwsS3Bucket", dataSourceAwsS3Bucket()},
		{DataSource, "dataSourceAwsS3BucketObject", dataSourceAwsS3BucketObject()},
		{DataSource, "dataSourceAwsSecretsManagerSecret", dataSourceAwsSecretsManagerSecret()},               // dataSourceAwsSecretsmanagerSecret(),
		{DataSource, "dataSourceAwsSecretsManagerSecretVersion", dataSourceAwsSecretsManagerSecretVersion()}, // dataSourceAwsSecretsmanagerSecretVersion(),
		{DataSource, "dataSourceAwsSecurityGroup", dataSourceAwsSecurityGroup()},
		{DataSource, "dataSourceAwsSnsTopic", dataSourceAwsSnsTopic()}, // dataSourceAwsSns(),
		{DataSource, "dataSourceAwsSqsQueue", dataSourceAwsSqsQueue()},
		{DataSource, "dataSourceAwsSsmParameter", dataSourceAwsSsmParameter()},
		{DataSource, "dataSourceAwsSubnet", dataSourceAwsSubnet()},
		{DataSource, "dataSourceAwsSubnetIDs", dataSourceAwsSubnetIDs()}, // dataSourceAwsSubnetIds(),
		{DataSource, "dataSourceAwsVpc", dataSourceAwsVpc()},
		{DataSource, "dataSourceAwsVpcDhcpOptions", dataSourceAwsVpcDhcpOptions()},
		{DataSource, "dataSourceAwsVpcEndpoint", dataSourceAwsVpcEndpoint()},
		{DataSource, "dataSourceAwsVpcEndpointService", dataSourceAwsVpcEndpointService()},
		{DataSource, "dataSourceAwsVpcPeeringConnection", dataSourceAwsVpcPeeringConnection()},
		{DataSource, "dataSourceAwsVpcs", dataSourceAwsVpcs()},
		{DataSource, "dataSourceAwsVpnGateway", dataSourceAwsVpnGateway()},
	}
}

func Resources() []TerraformResource {
	return []TerraformResource{
		{Resource, "resourceAwsAcmCertificate", resourceAwsAcmCertificate()},
		{Resource, "resourceAwsAcmCertificateValidation", resourceAwsAcmCertificateValidation()},
		{Resource, "resourceAwsAcmpcaCertificateAuthority", resourceAwsAcmpcaCertificateAuthority()},
		{Resource, "resourceAwsAmi", resourceAwsAmi()},
		{Resource, "resourceAwsAmiCopy", resourceAwsAmiCopy()},
		{Resource, "resourceAwsAmiFromInstance", resourceAwsAmiFromInstance()},
		{Resource, "resourceAwsAmiLaunchPermission", resourceAwsAmiLaunchPermission()},
		{Resource, "resourceAwsApiGatewayAccount", resourceAwsApiGatewayAccount()},
		{Resource, "resourceAwsApiGatewayApiKey", resourceAwsApiGatewayApiKey()},
		{Resource, "resourceAwsApiGatewayAuthorizer", resourceAwsApiGatewayAuthorizer()},
		{Resource, "resourceAwsApiGatewayBasePathMapping", resourceAwsApiGatewayBasePathMapping()},
		{Resource, "resourceAwsApiGatewayClientCertificate", resourceAwsApiGatewayClientCertificate()},
		{Resource, "resourceAwsApiGatewayDeployment", resourceAwsApiGatewayDeployment()},
		{Resource, "resourceAwsApiGatewayDocumentationPart", resourceAwsApiGatewayDocumentationPart()},
		{Resource, "resourceAwsApiGatewayDocumentationVersion", resourceAwsApiGatewayDocumentationVersion()},
		{Resource, "resourceAwsApiGatewayDomainName", resourceAwsApiGatewayDomainName()},
		{Resource, "resourceAwsApiGatewayGatewayResponse", resourceAwsApiGatewayGatewayResponse()},
		{Resource, "resourceAwsApiGatewayIntegration", resourceAwsApiGatewayIntegration()},
		{Resource, "resourceAwsApiGatewayIntegrationResponse", resourceAwsApiGatewayIntegrationResponse()},
		{Resource, "resourceAwsApiGatewayMethod", resourceAwsApiGatewayMethod()},
		{Resource, "resourceAwsApiGatewayMethodResponse", resourceAwsApiGatewayMethodResponse()},
		{Resource, "resourceAwsApiGatewayMethodSettings", resourceAwsApiGatewayMethodSettings()},
		{Resource, "resourceAwsApiGatewayModel", resourceAwsApiGatewayModel()},
		{Resource, "resourceAwsApiGatewayRequestValidator", resourceAwsApiGatewayRequestValidator()},
		{Resource, "resourceAwsApiGatewayResource", resourceAwsApiGatewayResource()},
		{Resource, "resourceAwsApiGatewayRestApi", resourceAwsApiGatewayRestApi()},
		{Resource, "resourceAwsApiGatewayStage", resourceAwsApiGatewayStage()},
		{Resource, "resourceAwsApiGatewayUsagePlan", resourceAwsApiGatewayUsagePlan()},
		{Resource, "resourceAwsApiGatewayUsagePlanKey", resourceAwsApiGatewayUsagePlanKey()},
		{Resource, "resourceAwsApiGatewayVpcLink", resourceAwsApiGatewayVpcLink()},
		{Resource, "resourceAwsAppCookieStickinessPolicy", resourceAwsAppCookieStickinessPolicy()},
		{Resource, "resourceAwsAppautoscalingPolicy", resourceAwsAppautoscalingPolicy()},
		{Resource, "resourceAwsAppautoscalingScheduledAction", resourceAwsAppautoscalingScheduledAction()},
		{Resource, "resourceAwsAppautoscalingTarget", resourceAwsAppautoscalingTarget()},
		{Resource, "resourceAwsAppsyncDatasource", resourceAwsAppsyncDatasource()},
		{Resource, "resourceAwsAppsyncGraphqlApi", resourceAwsAppsyncGraphqlApi()},
		{Resource, "resourceAwsAthenaDatabase", resourceAwsAthenaDatabase()},
		{Resource, "resourceAwsAthenaNamedQuery", resourceAwsAthenaNamedQuery()},
		{Resource, "resourceAwsAutoscalingAttachment", resourceAwsAutoscalingAttachment()},
		{Resource, "resourceAwsAutoscalingGroup", resourceAwsAutoscalingGroup()},
		// resourceAwsAutoscalingGroupWaiting(),
		{Resource, "resourceAwsAutoscalingLifecycleHook", resourceAwsAutoscalingLifecycleHook()},
		{Resource, "resourceAwsAutoscalingNotification", resourceAwsAutoscalingNotification()},
		{Resource, "resourceAwsAutoscalingPolicy", resourceAwsAutoscalingPolicy()},
		{Resource, "resourceAwsAutoscalingSchedule", resourceAwsAutoscalingSchedule()},
		{Resource, "resourceAwsBatchComputeEnvironment", resourceAwsBatchComputeEnvironment()},
		{Resource, "resourceAwsBatchJobDefinition", resourceAwsBatchJobDefinition()},
		{Resource, "resourceAwsBatchJobQueue", resourceAwsBatchJobQueue()},
		{Resource, "resourceAwsBudgetsBudget", resourceAwsBudgetsBudget()},
		{Resource, "resourceAwsCloud9EnvironmentEc2", resourceAwsCloud9EnvironmentEc2()},
		{Resource, "resourceAwsCloudFormationStack", resourceAwsCloudFormationStack()},                       // resourceAwsCloudformationStack(),
		{Resource, "resourceAwsCloudFrontDistribution", resourceAwsCloudFrontDistribution()},                 // resourceAwsCloudfrontDistribution(),
		{Resource, "resourceAwsCloudFrontOriginAccessIdentity", resourceAwsCloudFrontOriginAccessIdentity()}, // resourceAwsCloudfrontOriginAccessIdentity(),
		{Resource, "resourceAwsCloudTrail", resourceAwsCloudTrail()},                                         // resourceAwsCloudtrail(),
		{Resource, "resourceAwsCloudWatchDashboard", resourceAwsCloudWatchDashboard()},                       // resourceAwsCloudwatchDashboard(),
		{Resource, "resourceAwsCloudWatchEventPermission", resourceAwsCloudWatchEventPermission()},           // resourceAwsCloudwatchEventPermission(),
		{Resource, "resourceAwsCloudWatchEventRule", resourceAwsCloudWatchEventRule()},                       // resourceAwsCloudwatchEventRule(),
		{Resource, "resourceAwsCloudWatchEventTarget", resourceAwsCloudWatchEventTarget()},                   // resourceAwsCloudwatchEventTarget(),
		{Resource, "resourceAwsCloudWatchLogDestination", resourceAwsCloudWatchLogDestination()},             // resourceAwsCloudwatchLogDestination(),
		{Resource, "resourceAwsCloudWatchLogDestinationPolicy", resourceAwsCloudWatchLogDestinationPolicy()}, // resourceAwsCloudwatchLogDestinationPolicy(),
		{Resource, "resourceAwsCloudWatchLogGroup", resourceAwsCloudWatchLogGroup()},                         // resourceAwsCloudwatchLogGroup(),
		{Resource, "resourceAwsCloudWatchLogMetricFilter", resourceAwsCloudWatchLogMetricFilter()},           // resourceAwsCloudwatchLogMetricFilter(),
		{Resource, "resourceAwsCloudWatchLogResourcePolicy", resourceAwsCloudWatchLogResourcePolicy()},       // resourceAwsCloudwatchLogResourcePolicy(),
		{Resource, "resourceAwsCloudWatchLogStream", resourceAwsCloudWatchLogStream()},                       // resourceAwsCloudwatchLogStream(),
		{Resource, "resourceAwsCloudwatchLogSubscriptionFilter", resourceAwsCloudwatchLogSubscriptionFilter()},
		{Resource, "resourceAwsCloudWatchMetricAlarm", resourceAwsCloudWatchMetricAlarm()}, // resourceAwsCloudwatchMetricAlarm(),
		// resourceAwsCloudwatchMetricAlarmMigrate(),
		{Resource, "resourceAwsCodeBuildProject", resourceAwsCodeBuildProject()}, // resourceAwsCodebuildProject(),
		// resourceAwsCodebuildProjectMigrate(),
		{Resource, "resourceAwsCodeBuildWebhook", resourceAwsCodeBuildWebhook()},                     // resourceAwsCodebuildWebhook(),
		{Resource, "resourceAwsCodeCommitRepository", resourceAwsCodeCommitRepository()},             // resourceAwsCodecommitRepository(),
		{Resource, "resourceAwsCodeCommitTrigger", resourceAwsCodeCommitTrigger()},                   // resourceAwsCodecommitTrigger(),
		{Resource, "resourceAwsCodeDeployApp", resourceAwsCodeDeployApp()},                           // resourceAwsCodedeployApp(),
		{Resource, "resourceAwsCodeDeployDeploymentConfig", resourceAwsCodeDeployDeploymentConfig()}, // resourceAwsCodedeployDeploymentConfig(),
		{Resource, "resourceAwsCodeDeployDeploymentGroup", resourceAwsCodeDeployDeploymentGroup()},   // resourceAwsCodedeployDeploymentGroup(),
		{Resource, "resourceAwsCodePipeline", resourceAwsCodePipeline()},                             // resourceAwsCodepipeline(),
		{Resource, "resourceAwsCognitoIdentityPool", resourceAwsCognitoIdentityPool()},
		{Resource, "resourceAwsCognitoIdentityPoolRolesAttachment", resourceAwsCognitoIdentityPoolRolesAttachment()},
		{Resource, "resourceAwsCognitoIdentityProvider", resourceAwsCognitoIdentityProvider()},
		{Resource, "resourceAwsCognitoResourceServer", resourceAwsCognitoResourceServer()},
		{Resource, "resourceAwsCognitoUserGroup", resourceAwsCognitoUserGroup()},
		{Resource, "resourceAwsCognitoUserPool", resourceAwsCognitoUserPool()},
		{Resource, "resourceAwsCognitoUserPoolClient", resourceAwsCognitoUserPoolClient()},
		{Resource, "resourceAwsCognitoUserPoolDomain", resourceAwsCognitoUserPoolDomain()},
		{Resource, "resourceAwsConfigAggregateAuthorization", resourceAwsConfigAggregateAuthorization()},
		{Resource, "resourceAwsConfigConfigRule", resourceAwsConfigConfigRule()},
		{Resource, "resourceAwsConfigConfigurationAggregator", resourceAwsConfigConfigurationAggregator()},
		{Resource, "resourceAwsConfigConfigurationRecorder", resourceAwsConfigConfigurationRecorder()},
		{Resource, "resourceAwsConfigConfigurationRecorderStatus", resourceAwsConfigConfigurationRecorderStatus()},
		{Resource, "resourceAwsConfigDeliveryChannel", resourceAwsConfigDeliveryChannel()},
		{Resource, "resourceAwsCustomerGateway", resourceAwsCustomerGateway()},
		{Resource, "resourceAwsDaxCluster", resourceAwsDaxCluster()},
		{Resource, "resourceAwsDaxParameterGroup", resourceAwsDaxParameterGroup()},
		{Resource, "resourceAwsDaxSubnetGroup", resourceAwsDaxSubnetGroup()},
		{Resource, "resourceAwsDbEventSubscription", resourceAwsDbEventSubscription()},
		{Resource, "resourceAwsDbInstance", resourceAwsDbInstance()},
		{Resource, "resourceAwsDbOptionGroup", resourceAwsDbOptionGroup()},
		{Resource, "resourceAwsDbParameterGroup", resourceAwsDbParameterGroup()},
		{Resource, "resourceAwsDbSecurityGroup", resourceAwsDbSecurityGroup()},
		{Resource, "resourceAwsDbSnapshot", resourceAwsDbSnapshot()},
		{Resource, "resourceAwsDbSubnetGroup", resourceAwsDbSubnetGroup()},
		{Resource, "resourceAwsDefaultNetworkAcl", resourceAwsDefaultNetworkAcl()},
		{Resource, "resourceAwsDefaultRouteTable", resourceAwsDefaultRouteTable()},
		{Resource, "resourceAwsDefaultSecurityGroup", resourceAwsDefaultSecurityGroup()},
		{Resource, "resourceAwsDefaultSubnet", resourceAwsDefaultSubnet()},
		{Resource, "resourceAwsDefaultVpc", resourceAwsDefaultVpc()},
		{Resource, "resourceAwsDefaultVpcDhcpOptions", resourceAwsDefaultVpcDhcpOptions()},
		{Resource, "resourceAwsDevicefarmProject", resourceAwsDevicefarmProject()},
		{Resource, "resourceAwsDirectoryServiceConditionalForwarder", resourceAwsDirectoryServiceConditionalForwarder()},
		{Resource, "resourceAwsDirectoryServiceDirectory", resourceAwsDirectoryServiceDirectory()},
		{Resource, "resourceAwsDmsCertificate", resourceAwsDmsCertificate()},
		{Resource, "resourceAwsDmsEndpoint", resourceAwsDmsEndpoint()},
		{Resource, "resourceAwsDmsReplicationInstance", resourceAwsDmsReplicationInstance()},
		{Resource, "resourceAwsDmsReplicationSubnetGroup", resourceAwsDmsReplicationSubnetGroup()},
		{Resource, "resourceAwsDmsReplicationTask", resourceAwsDmsReplicationTask()},
		{Resource, "resourceAwsDxConnection", resourceAwsDxConnection()},
		{Resource, "resourceAwsDxConnectionAssociation", resourceAwsDxConnectionAssociation()},
		{Resource, "resourceAwsDxGateway", resourceAwsDxGateway()},
		{Resource, "resourceAwsDxGatewayAssociation", resourceAwsDxGatewayAssociation()},
		{Resource, "resourceAwsDxLag", resourceAwsDxLag()},
		{Resource, "resourceAwsDynamoDbGlobalTable", resourceAwsDynamoDbGlobalTable()}, // resourceAwsDynamodbGlobalTable(),
		{Resource, "resourceAwsDynamoDbTable", resourceAwsDynamoDbTable()},             // resourceAwsDynamodbTable(),
		{Resource, "resourceAwsDynamoDbTableItem", resourceAwsDynamoDbTableItem()},     // resourceAwsDynamodbTableItem(),
		// resourceAwsDynamodbTableMigrate(),
		{Resource, "resourceAwsEbsSnapshot", resourceAwsEbsSnapshot()},
		{Resource, "resourceAwsEbsVolume", resourceAwsEbsVolume()},
		{Resource, "resourceAwsEcrLifecyclePolicy", resourceAwsEcrLifecyclePolicy()},
		{Resource, "resourceAwsEcrRepository", resourceAwsEcrRepository()},
		{Resource, "resourceAwsEcrRepositoryPolicy", resourceAwsEcrRepositoryPolicy()},
		{Resource, "resourceAwsEcsCluster", resourceAwsEcsCluster()},
		{Resource, "resourceAwsEcsService", resourceAwsEcsService()},
		{Resource, "resourceAwsEcsTaskDefinition", resourceAwsEcsTaskDefinition()},
		// resourceAwsEcsTaskDefinitionMigrate(),
		{Resource, "resourceAwsEfsFileSystem", resourceAwsEfsFileSystem()},
		{Resource, "resourceAwsEfsMountTarget", resourceAwsEfsMountTarget()},
		{Resource, "resourceAwsEgressOnlyInternetGateway", resourceAwsEgressOnlyInternetGateway()},
		{Resource, "resourceAwsEip", resourceAwsEip()},
		{Resource, "resourceAwsEipAssociation", resourceAwsEipAssociation()},
		{Resource, "resourceAwsEksCluster", resourceAwsEksCluster()},
		{Resource, "resourceAwsElasticBeanstalkApplication", resourceAwsElasticBeanstalkApplication()},
		{Resource, "resourceAwsElasticBeanstalkApplicationVersion", resourceAwsElasticBeanstalkApplicationVersion()},
		{Resource, "resourceAwsElasticBeanstalkConfigurationTemplate", resourceAwsElasticBeanstalkConfigurationTemplate()},
		{Resource, "resourceAwsElasticBeanstalkEnvironment", resourceAwsElasticBeanstalkEnvironment()},
		// resourceAwsElasticBeanstalkEnvironmentMigrate(),
		{Resource, "resourceAwsElasticTranscoderPipeline", resourceAwsElasticTranscoderPipeline()},
		{Resource, "resourceAwsElasticTranscoderPreset", resourceAwsElasticTranscoderPreset()},
		{Resource, "resourceAwsElasticacheCluster", resourceAwsElasticacheCluster()},
		{Resource, "resourceAwsElasticacheParameterGroup", resourceAwsElasticacheParameterGroup()},
		{Resource, "resourceAwsElasticacheReplicationGroup", resourceAwsElasticacheReplicationGroup()},
		// resourceAwsElasticacheReplicationGroupMigrate(),
		{Resource, "resourceAwsElasticacheSecurityGroup", resourceAwsElasticacheSecurityGroup()},
		{Resource, "resourceAwsElasticacheSubnetGroup", resourceAwsElasticacheSubnetGroup()},
		{Resource, "resourceAwsElasticSearchDomain", resourceAwsElasticSearchDomain()},             // resourceAwsElasticsearchDomain(),
		{Resource, "resourceAwsElasticSearchDomainPolicy", resourceAwsElasticSearchDomainPolicy()}, // resourceAwsElasticsearchDomainPolicy(),
		{Resource, "resourceAwsElb", resourceAwsElb()},
		{Resource, "resourceAwsElbAttachment", resourceAwsElbAttachment()},
		{Resource, "resourceAwsEMRCluster", resourceAwsEMRCluster()},                             // resourceAwsEmrCluster(),
		{Resource, "resourceAwsEMRInstanceGroup", resourceAwsEMRInstanceGroup()},                 // resourceAwsEmrInstanceGroup(),
		{Resource, "resourceAwsEMRSecurityConfiguration", resourceAwsEMRSecurityConfiguration()}, // resourceAwsEmrSecurityConfiguration(),
		{Resource, "resourceAwsFlowLog", resourceAwsFlowLog()},
		{Resource, "resourceAwsGameliftAlias", resourceAwsGameliftAlias()},
		{Resource, "resourceAwsGameliftBuild", resourceAwsGameliftBuild()},
		{Resource, "resourceAwsGameliftFleet", resourceAwsGameliftFleet()},
		{Resource, "resourceAwsGlacierVault", resourceAwsGlacierVault()},
		{Resource, "resourceAwsGlueCatalogDatabase", resourceAwsGlueCatalogDatabase()},
		{Resource, "resourceAwsGlueCatalogTable", resourceAwsGlueCatalogTable()},
		{Resource, "resourceAwsGlueClassifier", resourceAwsGlueClassifier()},
		{Resource, "resourceAwsGlueConnection", resourceAwsGlueConnection()},
		{Resource, "resourceAwsGlueCrawler", resourceAwsGlueCrawler()},
		{Resource, "resourceAwsGlueJob", resourceAwsGlueJob()},
		{Resource, "resourceAwsGlueTrigger", resourceAwsGlueTrigger()},
		{Resource, "resourceAwsGuardDutyDetector", resourceAwsGuardDutyDetector()},             // resourceAwsGuarddutyDetector(),
		{Resource, "resourceAwsGuardDutyIpset", resourceAwsGuardDutyIpset()},                   // resourceAwsGuarddutyIpset(),
		{Resource, "resourceAwsGuardDutyMember", resourceAwsGuardDutyMember()},                 // resourceAwsGuarddutyMember(),
		{Resource, "resourceAwsGuardDutyThreatintelset", resourceAwsGuardDutyThreatintelset()}, // resourceAwsGuarddutyThreatintelset(),
		{Resource, "resourceAwsIamAccessKey", resourceAwsIamAccessKey()},
		{Resource, "resourceAwsIamAccountAlias", resourceAwsIamAccountAlias()},
		{Resource, "resourceAwsIamAccountPasswordPolicy", resourceAwsIamAccountPasswordPolicy()},
		{Resource, "resourceAwsIamGroup", resourceAwsIamGroup()},
		{Resource, "resourceAwsIamGroupMembership", resourceAwsIamGroupMembership()},
		{Resource, "resourceAwsIamGroupPolicy", resourceAwsIamGroupPolicy()},
		{Resource, "resourceAwsIamGroupPolicyAttachment", resourceAwsIamGroupPolicyAttachment()},
		{Resource, "resourceAwsIamInstanceProfile", resourceAwsIamInstanceProfile()},
		{Resource, "resourceAwsIamOpenIDConnectProvider", resourceAwsIamOpenIDConnectProvider()}, // resourceAwsIamOpenidConnectProvider(),
		{Resource, "resourceAwsIamPolicy", resourceAwsIamPolicy()},
		{Resource, "resourceAwsIamPolicyAttachment", resourceAwsIamPolicyAttachment()},
		{Resource, "resourceAwsIamRole", resourceAwsIamRole()},
		{Resource, "resourceAwsIamRolePolicy", resourceAwsIamRolePolicy()},
		{Resource, "resourceAwsIamRolePolicyAttachment", resourceAwsIamRolePolicyAttachment()},
		{Resource, "resourceAwsIamSamlProvider", resourceAwsIamSamlProvider()},
		{Resource, "resourceAwsIAMServerCertificate", resourceAwsIAMServerCertificate()}, // resourceAwsIamServerCertificate(),
		{Resource, "resourceAwsIamServiceLinkedRole", resourceAwsIamServiceLinkedRole()},
		{Resource, "resourceAwsIamUser", resourceAwsIamUser()},
		{Resource, "resourceAwsIamUserGroupMembership", resourceAwsIamUserGroupMembership()},
		{Resource, "resourceAwsIamUserLoginProfile", resourceAwsIamUserLoginProfile()},
		{Resource, "resourceAwsIamUserPolicy", resourceAwsIamUserPolicy()},
		{Resource, "resourceAwsIamUserPolicyAttachment", resourceAwsIamUserPolicyAttachment()},
		{Resource, "resourceAwsIamUserSshKey", resourceAwsIamUserSshKey()},
		{Resource, "resourceAWSInspectorAssessmentTarget", resourceAWSInspectorAssessmentTarget()},     // resourceAwsInspectorAssessmentTarget(),
		{Resource, "resourceAWSInspectorAssessmentTemplate", resourceAWSInspectorAssessmentTemplate()}, // resourceAwsInspectorAssessmentTemplate(),
		{Resource, "resourceAWSInspectorResourceGroup", resourceAWSInspectorResourceGroup()},           // resourceAwsInspectorResourceGroup(),
		{Resource, "resourceAwsInstance", resourceAwsInstance()},
		// resourceAwsInstanceMigrate(),
		{Resource, "resourceAwsInternetGateway", resourceAwsInternetGateway()},
		{Resource, "resourceAwsIotCertificate", resourceAwsIotCertificate()},
		{Resource, "resourceAwsIotPolicy", resourceAwsIotPolicy()},
		{Resource, "resourceAwsIotThing", resourceAwsIotThing()},
		{Resource, "resourceAwsIotThingType", resourceAwsIotThingType()},
		{Resource, "resourceAwsIotTopicRule", resourceAwsIotTopicRule()},
		{Resource, "resourceAwsKeyPair", resourceAwsKeyPair()},
		// resourceAwsKeyPairMigrate(),
		{Resource, "resourceAwsKinesisFirehoseDeliveryStream", resourceAwsKinesisFirehoseDeliveryStream()},
		// resourceAwsKinesisFirehoseDeliveryStreamMigrate(),
		{Resource, "resourceAwsKinesisStream", resourceAwsKinesisStream()},
		{Resource, "resourceAwsKmsAlias", resourceAwsKmsAlias()},
		{Resource, "resourceAwsKmsGrant", resourceAwsKmsGrant()},
		{Resource, "resourceAwsKmsKey", resourceAwsKmsKey()},
		{Resource, "resourceAwsLambdaAlias", resourceAwsLambdaAlias()},
		{Resource, "resourceAwsLambdaEventSourceMapping", resourceAwsLambdaEventSourceMapping()},
		{Resource, "resourceAwsLambdaFunction", resourceAwsLambdaFunction()},
		{Resource, "resourceAwsLambdaPermission", resourceAwsLambdaPermission()},
		{Resource, "resourceAwsLaunchConfiguration", resourceAwsLaunchConfiguration()},
		{Resource, "resourceAwsLaunchTemplate", resourceAwsLaunchTemplate()},
		{Resource, "resourceAwsLb", resourceAwsLb()},
		{Resource, "resourceAwsLBCookieStickinessPolicy", resourceAwsLBCookieStickinessPolicy()}, // resourceAwsLbCookieStickinessPolicy(),
		{Resource, "resourceAwsLbListener", resourceAwsLbListener()},
		{Resource, "resourceAwsLbListenerCertificate", resourceAwsLbListenerCertificate()},
		{Resource, "resourceAwsLbbListenerRule", resourceAwsLbbListenerRule()},               // resourceAwsLbListenerRule(),
		{Resource, "resourceAwsLBSSLNegotiationPolicy", resourceAwsLBSSLNegotiationPolicy()}, // resourceAwsLbSslNegotiationPolicy(),
		{Resource, "resourceAwsLbTargetGroup", resourceAwsLbTargetGroup()},
		{Resource, "resourceAwsLbTargetGroupAttachment", resourceAwsLbTargetGroupAttachment()},
		{Resource, "resourceAwsLightsailDomain", resourceAwsLightsailDomain()},
		{Resource, "resourceAwsLightsailInstance", resourceAwsLightsailInstance()},
		{Resource, "resourceAwsLightsailKeyPair", resourceAwsLightsailKeyPair()},
		{Resource, "resourceAwsLightsailStaticIp", resourceAwsLightsailStaticIp()},
		{Resource, "resourceAwsLightsailStaticIpAttachment", resourceAwsLightsailStaticIpAttachment()},
		{Resource, "resourceAwsLoadBalancerBackendServerPolicies", resourceAwsLoadBalancerBackendServerPolicies()}, // resourceAwsLoadBalancerBackendServerPolicy(),
		{Resource, "resourceAwsLoadBalancerListenerPolicies", resourceAwsLoadBalancerListenerPolicies()},           // resourceAwsLoadBalancerListenerPolicy(),
		{Resource, "resourceAwsLoadBalancerPolicy", resourceAwsLoadBalancerPolicy()},
		{Resource, "resourceAwsMainRouteTableAssociation", resourceAwsMainRouteTableAssociation()},
		{Resource, "resourceAwsMediaStoreContainer", resourceAwsMediaStoreContainer()},
		{Resource, "resourceAwsMqBroker", resourceAwsMqBroker()},
		{Resource, "resourceAwsMqConfiguration", resourceAwsMqConfiguration()},
		{Resource, "resourceAwsNatGateway", resourceAwsNatGateway()},
		{Resource, "resourceAwsNeptuneClusterParameterGroup", resourceAwsNeptuneClusterParameterGroup()},
		{Resource, "resourceAwsNeptuneParameterGroup", resourceAwsNeptuneParameterGroup()},
		{Resource, "resourceAwsNeptuneSubnetGroup", resourceAwsNeptuneSubnetGroup()},
		{Resource, "resourceAwsNetworkAcl", resourceAwsNetworkAcl()},
		{Resource, "resourceAwsNetworkAclRule", resourceAwsNetworkAclRule()},
		{Resource, "resourceAwsNetworkInterface", resourceAwsNetworkInterface()},
		{Resource, "resourceAwsNetworkInterfaceAttachment", resourceAwsNetworkInterfaceAttachment()},
		{Resource, "resourceAwsNetworkInterfaceSGAttachment", resourceAwsNetworkInterfaceSGAttachment()}, // resourceAwsNetworkInterfaceSgAttachment(),
		{Resource, "resourceAwsOpsworksApplication", resourceAwsOpsworksApplication()},
		{Resource, "resourceAwsOpsworksCustomLayer", resourceAwsOpsworksCustomLayer()},
		{Resource, "resourceAwsOpsworksGangliaLayer", resourceAwsOpsworksGangliaLayer()},
		{Resource, "resourceAwsOpsworksHaproxyLayer", resourceAwsOpsworksHaproxyLayer()},
		{Resource, "resourceAwsOpsworksInstance", resourceAwsOpsworksInstance()},
		{Resource, "resourceAwsOpsworksJavaAppLayer", resourceAwsOpsworksJavaAppLayer()},
		{Resource, "resourceAwsOpsworksMemcachedLayer", resourceAwsOpsworksMemcachedLayer()},
		{Resource, "resourceAwsOpsworksMysqlLayer", resourceAwsOpsworksMysqlLayer()},
		{Resource, "resourceAwsOpsworksNodejsAppLayer", resourceAwsOpsworksNodejsAppLayer()},
		{Resource, "resourceAwsOpsworksPermission", resourceAwsOpsworksPermission()},
		{Resource, "resourceAwsOpsworksPhpAppLayer", resourceAwsOpsworksPhpAppLayer()},
		{Resource, "resourceAwsOpsworksRailsAppLayer", resourceAwsOpsworksRailsAppLayer()},
		{Resource, "resourceAwsOpsworksRdsDbInstance", resourceAwsOpsworksRdsDbInstance()},
		{Resource, "resourceAwsOpsworksStack", resourceAwsOpsworksStack()},
		{Resource, "resourceAwsOpsworksStaticWebLayer", resourceAwsOpsworksStaticWebLayer()},
		{Resource, "resourceAwsOpsworksUserProfile", resourceAwsOpsworksUserProfile()},
		{Resource, "resourceAwsOrganizationsAccount", resourceAwsOrganizationsAccount()},
		{Resource, "resourceAwsOrganizationsOrganization", resourceAwsOrganizationsOrganization()},
		{Resource, "resourceAwsOrganizationsPolicy", resourceAwsOrganizationsPolicy()},
		{Resource, "resourceAwsOrganizationsPolicyAttachment", resourceAwsOrganizationsPolicyAttachment()},
		{Resource, "resourceAwsPlacementGroup", resourceAwsPlacementGroup()},
		{Resource, "resourceAwsProxyProtocolPolicy", resourceAwsProxyProtocolPolicy()},
		{Resource, "resourceAwsRDSCluster", resourceAwsRDSCluster()},                             // resourceAwsRdsCluster(),
		{Resource, "resourceAwsRDSClusterInstance", resourceAwsRDSClusterInstance()},             // resourceAwsRdsClusterInstance(),
		{Resource, "resourceAwsRDSClusterParameterGroup", resourceAwsRDSClusterParameterGroup()}, // resourceAwsRdsClusterParameterGroup(),
		{Resource, "resourceAwsRedshiftCluster", resourceAwsRedshiftCluster()},
		{Resource, "resourceAwsRedshiftParameterGroup", resourceAwsRedshiftParameterGroup()},
		{Resource, "resourceAwsRedshiftSecurityGroup", resourceAwsRedshiftSecurityGroup()},
		{Resource, "resourceAwsRedshiftSubnetGroup", resourceAwsRedshiftSubnetGroup()},
		{Resource, "resourceAwsRoute", resourceAwsRoute()},
		{Resource, "resourceAwsRoute53DelegationSet", resourceAwsRoute53DelegationSet()},
		{Resource, "resourceAwsRoute53HealthCheck", resourceAwsRoute53HealthCheck()},
		{Resource, "resourceAwsRoute53QueryLog", resourceAwsRoute53QueryLog()},
		{Resource, "resourceAwsRoute53Record", resourceAwsRoute53Record()},
		// resourceAwsRoute53RecordMigrate(),
		{Resource, "resourceAwsRoute53Zone", resourceAwsRoute53Zone()},
		{Resource, "resourceAwsRoute53ZoneAssociation", resourceAwsRoute53ZoneAssociation()},
		{Resource, "resourceAwsRouteTable", resourceAwsRouteTable()},
		{Resource, "resourceAwsRouteTableAssociation", resourceAwsRouteTableAssociation()},
		{Resource, "resourceAwsS3Bucket", resourceAwsS3Bucket()},
		{Resource, "resourceAwsS3BucketMetric", resourceAwsS3BucketMetric()},
		{Resource, "resourceAwsS3BucketNotification", resourceAwsS3BucketNotification()},
		{Resource, "resourceAwsS3BucketObject", resourceAwsS3BucketObject()},
		{Resource, "resourceAwsS3BucketPolicy", resourceAwsS3BucketPolicy()},
		{Resource, "resourceAwsSecretsManagerSecret", resourceAwsSecretsManagerSecret()},               // resourceAwsSecretsmanagerSecret(),
		{Resource, "resourceAwsSecretsManagerSecretVersion", resourceAwsSecretsManagerSecretVersion()}, // resourceAwsSecretsmanagerSecretVersion(),
		{Resource, "resourceAwsSecurityGroup", resourceAwsSecurityGroup()},
		// resourceAwsSecurityGroupMigrate(),
		{Resource, "resourceAwsSecurityGroupRule", resourceAwsSecurityGroupRule()},
		// resourceAwsSecurityGroupRuleMigrate(),
		{Resource, "resourceAwsServiceDiscoveryPrivateDnsNamespace", resourceAwsServiceDiscoveryPrivateDnsNamespace()},
		{Resource, "resourceAwsServiceDiscoveryPublicDnsNamespace", resourceAwsServiceDiscoveryPublicDnsNamespace()},
		{Resource, "resourceAwsServiceDiscoveryService", resourceAwsServiceDiscoveryService()},
		// resourceAwsServiceDiscoveryServiceMigrate(),
		{Resource, "resourceAwsServiceCatalogPortfolio", resourceAwsServiceCatalogPortfolio()}, // resourceAwsServicecatalogPortfolio(),
		{Resource, "resourceAwsSesActiveReceiptRuleSet", resourceAwsSesActiveReceiptRuleSet()},
		{Resource, "resourceAwsSesConfigurationSet", resourceAwsSesConfigurationSet()},
		{Resource, "resourceAwsSesDomainDkim", resourceAwsSesDomainDkim()},
		{Resource, "resourceAwsSesDomainIdentity", resourceAwsSesDomainIdentity()},
		{Resource, "resourceAwsSesDomainIdentityVerification", resourceAwsSesDomainIdentityVerification()},
		{Resource, "resourceAwsSesDomainMailFrom", resourceAwsSesDomainMailFrom()},
		{Resource, "resourceAwsSesEventDestination", resourceAwsSesEventDestination()},
		{Resource, "resourceAwsSesNotificationTopic", resourceAwsSesNotificationTopic()}, // resourceAwsSesIdentityNotificationTopic(),
		{Resource, "resourceAwsSesReceiptFilter", resourceAwsSesReceiptFilter()},
		{Resource, "resourceAwsSesReceiptRule", resourceAwsSesReceiptRule()},
		{Resource, "resourceAwsSesReceiptRuleSet", resourceAwsSesReceiptRuleSet()},
		{Resource, "resourceAwsSesTemplate", resourceAwsSesTemplate()},
		{Resource, "resourceAwsSfnActivity", resourceAwsSfnActivity()},
		{Resource, "resourceAwsSfnStateMachine", resourceAwsSfnStateMachine()},
		{Resource, "resourceAwsSimpleDBDomain", resourceAwsSimpleDBDomain()}, // resourceAwsSimpledbDomain(),
		{Resource, "resourceAwsSnapshotCreateVolumePermission", resourceAwsSnapshotCreateVolumePermission()},
		{Resource, "resourceAwsSnsPlatformApplication", resourceAwsSnsPlatformApplication()},
		{Resource, "resourceAwsSnsSmsPreferences", resourceAwsSnsSmsPreferences()},
		{Resource, "resourceAwsSnsTopic", resourceAwsSnsTopic()},
		{Resource, "resourceAwsSnsTopicPolicy", resourceAwsSnsTopicPolicy()},
		{Resource, "resourceAwsSnsTopicSubscription", resourceAwsSnsTopicSubscription()},
		{Resource, "resourceAwsSpotDataFeedSubscription", resourceAwsSpotDataFeedSubscription()}, // resourceAwsSpotDatafeedSubscription(),
		{Resource, "resourceAwsSpotFleetRequest", resourceAwsSpotFleetRequest()},
		// resourceAwsSpotFleetRequestMigrate(),
		{Resource, "resourceAwsSpotInstanceRequest", resourceAwsSpotInstanceRequest()},
		{Resource, "resourceAwsSqsQueue", resourceAwsSqsQueue()},
		{Resource, "resourceAwsSqsQueuePolicy", resourceAwsSqsQueuePolicy()},
		// resourceAwsSqsQueuePolicyMigrate(),
		{Resource, "resourceAwsSsmActivation", resourceAwsSsmActivation()},
		{Resource, "resourceAwsSsmAssociation", resourceAwsSsmAssociation()},
		// resourceAwsSsmAssociationMigrate(),
		{Resource, "resourceAwsSsmDocument", resourceAwsSsmDocument()},
		{Resource, "resourceAwsSsmMaintenanceWindow", resourceAwsSsmMaintenanceWindow()},
		{Resource, "resourceAwsSsmMaintenanceWindowTarget", resourceAwsSsmMaintenanceWindowTarget()},
		{Resource, "resourceAwsSsmMaintenanceWindowTask", resourceAwsSsmMaintenanceWindowTask()},
		{Resource, "resourceAwsSsmParameter", resourceAwsSsmParameter()},
		{Resource, "resourceAwsSsmPatchBaseline", resourceAwsSsmPatchBaseline()},
		{Resource, "resourceAwsSsmPatchGroup", resourceAwsSsmPatchGroup()},
		{Resource, "resourceAwsSsmResourceDataSync", resourceAwsSsmResourceDataSync()},
		{Resource, "resourceAwsSubnet", resourceAwsSubnet()},
		// resourceAwsSubnetMigrate(),
		{Resource, "resourceAwsVolumeAttachment", resourceAwsVolumeAttachment()},
		{Resource, "resourceAwsVpc", resourceAwsVpc()},
		{Resource, "resourceAwsVpcDhcpOptions", resourceAwsVpcDhcpOptions()},
		{Resource, "resourceAwsVpcDhcpOptionsAssociation", resourceAwsVpcDhcpOptionsAssociation()},
		{Resource, "resourceAwsVpcEndpoint", resourceAwsVpcEndpoint()},
		{Resource, "resourceAwsVpcEndpointConnectionNotification", resourceAwsVpcEndpointConnectionNotification()},
		{Resource, "resourceAwsVpcEndpointRouteTableAssociation", resourceAwsVpcEndpointRouteTableAssociation()},
		{Resource, "resourceAwsVpcEndpointService", resourceAwsVpcEndpointService()},
		{Resource, "resourceAwsVpcEndpointServiceAllowedPrincipal", resourceAwsVpcEndpointServiceAllowedPrincipal()},
		{Resource, "resourceAwsVpcEndpointSubnetAssociation", resourceAwsVpcEndpointSubnetAssociation()},
		// resourceAwsVpcMigrate(),
		{Resource, "resourceAwsVpcPeeringConnection", resourceAwsVpcPeeringConnection()},
		{Resource, "resourceAwsVpcPeeringConnectionAccepter", resourceAwsVpcPeeringConnectionAccepter()},
		{Resource, "resourceAwsVpcPeeringConnectionOptions", resourceAwsVpcPeeringConnectionOptions()},
		{Resource, "resourceAwsVpnConnection", resourceAwsVpnConnection()},
		{Resource, "resourceAwsVpnConnectionRoute", resourceAwsVpnConnectionRoute()},
		{Resource, "resourceAwsVpnGateway", resourceAwsVpnGateway()},
		{Resource, "resourceAwsVpnGatewayAttachment", resourceAwsVpnGatewayAttachment()},
		{Resource, "resourceAwsVpnGatewayRoutePropagation", resourceAwsVpnGatewayRoutePropagation()},
		{Resource, "resourceAwsWafByteMatchSet", resourceAwsWafByteMatchSet()},
		{Resource, "resourceAwsWafGeoMatchSet", resourceAwsWafGeoMatchSet()},
		{Resource, "resourceAwsWafIPSet", resourceAwsWafIPSet()}, // resourceAwsWafIpset(),
		{Resource, "resourceAwsWafRateBasedRule", resourceAwsWafRateBasedRule()},
		{Resource, "resourceAwsWafRegexMatchSet", resourceAwsWafRegexMatchSet()},
		{Resource, "resourceAwsWafRegexPatternSet", resourceAwsWafRegexPatternSet()},
		{Resource, "resourceAwsWafRule", resourceAwsWafRule()},
		{Resource, "resourceAwsWafRuleGroup", resourceAwsWafRuleGroup()},
		{Resource, "resourceAwsWafSizeConstraintSet", resourceAwsWafSizeConstraintSet()},
		{Resource, "resourceAwsWafSqlInjectionMatchSet", resourceAwsWafSqlInjectionMatchSet()},
		{Resource, "resourceAwsWafWebAcl", resourceAwsWafWebAcl()},
		{Resource, "resourceAwsWafXssMatchSet", resourceAwsWafXssMatchSet()},
		{Resource, "resourceAwsWafRegionalByteMatchSet", resourceAwsWafRegionalByteMatchSet()},                 // resourceAwsWafregionalByteMatchSet(),
		{Resource, "resourceAwsWafRegionalGeoMatchSet", resourceAwsWafRegionalGeoMatchSet()},                   // resourceAwsWafregionalGeoMatchSet(),
		{Resource, "resourceAwsWafRegionalIPSet", resourceAwsWafRegionalIPSet()},                               // resourceAwsWafregionalIpset(),
		{Resource, "resourceAwsWafRegionalRateBasedRule", resourceAwsWafRegionalRateBasedRule()},               // resourceAwsWafregionalRateBasedRule(),
		{Resource, "resourceAwsWafRegionalRegexMatchSet", resourceAwsWafRegionalRegexMatchSet()},               // resourceAwsWafregionalRegexMatchSet(),
		{Resource, "resourceAwsWafRegionalRegexPatternSet", resourceAwsWafRegionalRegexPatternSet()},           // resourceAwsWafregionalRegexPatternSet(),
		{Resource, "resourceAwsWafRegionalRule", resourceAwsWafRegionalRule()},                                 // resourceAwsWafregionalRule(),
		{Resource, "resourceAwsWafRegionalRuleGroup", resourceAwsWafRegionalRuleGroup()},                       // resourceAwsWafregionalRuleGroup(),
		{Resource, "resourceAwsWafRegionalSizeConstraintSet", resourceAwsWafRegionalSizeConstraintSet()},       // resourceAwsWafregionalSizeConstraintSet(),
		{Resource, "resourceAwsWafRegionalSqlInjectionMatchSet", resourceAwsWafRegionalSqlInjectionMatchSet()}, // resourceAwsWafregionalSqlInjectionMatchSet(),
		{Resource, "resourceAwsWafRegionalWebAcl", resourceAwsWafRegionalWebAcl()},                             // resourceAwsWafregionalWebAcl(),
		{Resource, "resourceAwsWafRegionalWebAclAssociation", resourceAwsWafRegionalWebAclAssociation()},       // resourceAwsWafregionalWebAclAssociation(),
		{Resource, "resourceAwsWafRegionalXssMatchSet", resourceAwsWafRegionalXssMatchSet()},                   // resourceAwsWafregionalXssMatchSet(),
	}
}
